Parallel-in-Time/pySDC

- examples/advection/ProblemClass.py
- examples/advection/playground.py
Changed the sign of the A matrix in the advection example from + to -: The PDE is
u_t + u_x = 0
If A is the approximation of d_x, the semi-discrete version is
u_t + A u = 0
so that the IVP form that SDC is based on reads
u_t = -A u.
> fixed sign of matrix in advection example

- examples/boussinesq_2d_imex/ProblemClass.py
- examples/boussinesq_2d_imex/playground.py
- adds a logging and callback object definition to the ProblemClass of the boussinesq example
- the callback object is used in SciPy GMRES to track the number of required iterations and the residual
- the logging object tracks the total number of iterations over the whole integration
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/parallel-in-time/pysdc/24)
> added counter for required GMRES iterations in boussinesq example

- examples/boussinesq_2d_imex/ProblemClass.py
- examples/boussinesq_2d_imex/buildBoussinesq2DMatrix.py
- examples/boussinesq_2d_imex/playground.py
Adds a basic two level hierarchy for the boussinesq example. At the moment, coarse and fine level use the same discretization.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/parallel-in-time/pysdc/25)
> basic two-level hierarchy for boussinesq now running

- examples/boussinesq_2d_imex/TransferClass.py
Add transfer class for boussinesq example.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/parallel-in-time/pysdc/27)
> add transfer class for boussineqs

- examples/boussinesq_2d_imex/HookClass.py
- examples/boussinesq_2d_imex/ProblemClass.py
- examples/boussinesq_2d_imex/playground.py
Minor changes and fixed parameters. Now runs PFASST with 16 processors - alas, ultimately the last process needs 16 iterations to converge.
> minor tweaks and parameter changes

- pySDC/CollocationClasses.py
- the assert in the Legendre class checked for > 1 but should check >= 1 (M=1 is a valid input for Legendre nodes)
- for consistency, changed asserts for other node types to >= instead of >
> Fixed assert about node numbers on Legendre class

- examples/SWFW/ProblemClass.py
- tests/test_imexsweeper.py
Introduces a number of tests for the IMEX sweeper.
- checks that matrix formulation of sweep is equivalent to node-to-node sweep
- checks that update function matches node-to-node sweeps plus update (for Lobatto nodes, need to fix #52 to pass)
- other tests making sure the IMEX sweeper does what is expected.
> test_imexsweeper

- examples/acoustic_1d_imex/ProblemClass_conv.py
- examples/acoustic_1d_imex/plotconvdata.py
- examples/acoustic_1d_imex/runconvergence.py
- examples/acoustic_1d_imex/runitererror.py
- examples/fwsw/run_convergence.py
Convergence plots now use slightly different parameter. In particular, instead of  a single sine mode, the example now uses two sine modes with k=1 and k=5.
> Tweaked parameter for convergence plots

- examples/boussinesq_2d_imex/plotgmrescounter.py
- examples/boussinesq_2d_imex/rungmrescounter.py
Changes the order how the different schemes are run, to make sure the reference solution is correctly computed with a fine GMRES tolerance.
> Fix error estimation

- pySDC/CollocationClasses.py
- tests/test_collocation.py
- tests/test_imexsweeper.py
test_collocation and test_imexsweeper now performs tests for four types of quadrature nodes: Legendre, Lobatto, Radau_Right and Radau_Left
Fixes #63
> Test all node types

- examples/fwsw/plot_stability.py
- pySDC/sweeper_classes/imex_1st_order.py
- tests/test_imexsweeper.py
Augments the IMEX sweeper with a range of functions to generate the matrices representing one or multiple sweeps in matrix form. Having those functions all in one place allows to automate their testing.
Modifies test_imexsweeper to verify that matrix sweeps and normal sweeps are equivalent.
Fixes #57
> Matrix functions in sweeper

- examples/boussinesq_2d_imex/plotgmrescounter.py
- examples/boussinesq_2d_imex/rungmrescounter.py
- examples/boussinesq_2d_imex/standard_integrators.py
> add split-explicit method by Knoth et al.

- examples/acoustic_1d_imex/runmultiscale.py
- examples/acoustic_1d_imex/standard_integrators.py
- examples/boussinesq_2d_imex/rungmrescounter.py
- examples/boussinesq_2d_imex/standard_integrators.py
> add fifth order DIRK method to 1d acoustic IMEX and boussinesq example

- pySDC/CollocationClasses.py
- tests/test_collocation.py
Extends `CollocationClasses.py` to provide two new classes for equidistant nodes, one where both endpoints are excluded, one where only the left endpoint is excluded.
> equidistant nodes

- .gitignore
- pySDC/core/Collocation.py
Hi Robert,
the original implementation of the QMatrix computation was suffering from 2 main downsides
1. each time _get_weights was called, it need to re-compute the same Barycentric interpolation polynomials that were already computed for the previous node => redundancy
2.  the use of quad is very expensive, and probably not needed since the integrand function is a polynomial of order M.
So I put the computation of the Barycentric polynomials directly in the _gen_QMatrix function, and changed the quad interpolation with an order M interpolation using Legendre nodes and weights. This does not change the dependencies of pySDC (nodes and weights come from scipy, quadrature use vectorized numpy operations). It improves a little bit the computation for large number of nodes (for M=100, …
> Small performance boost for QMatrix computation

- pySDC/core/Hooks.py
- pySDC/core/Level.py
- pySDC/helpers/stats_helper.py
- pySDC/implementations/controller_classes/controller_nonMPI.py
- pySDC/projects/error_estimation/piline_hotrod_adaptivity.py
Not just the last step, but the steps of the last block are shortened to go to Tend. I find this more consistent with the current state of adaptivity. It is set in the function that sets the new steps from whatever is stored in level.status.dt_new, so this can be made problem specific.
> Adaptivity Tend fix

- pySDC/core/Controller.py
- requirements.txt
Looks like this now in the terminal: 
```
controller - INFO: Welcome to the one and only, really very astonishing and 87.3% bug free
_____ _____   _____ 
/ ____|  __ \ / ____|
_ __  _   _| (___ | |  | | |     
| '_ \| | | |\___ \| |  | | |     
| |_) | |_| |____) | |__| | |____ 
| .__/ \__, |_____/|_____/ \_____|
| |     __/ |                     
|_|    |___/                      
```
> Added a welcome message, but it's kind of stupid. Please suggest something more reasonable

- pySDC/core/Sweeper.py
This allows to set a local random seed for the sweeper which makes sure the initial guesses are reproducible.
As far as I can tell there are no tests that depend on a specific random seed inside the sweeper, but be aware that this will change the behaviour compared to previously, where there was either none or a global random seed specified.
Global random seeds are outdated because you may set a different random seed for a completely independent different random process somewhere else, which would impact the reproducibility of the other random processes.
Computing contraction factors for preconditioners, anyways, seems to work much better with random initial guess.
If you would don't like these small PRs because they produce so many emails, please let me know.
> Added random generator to the Sweeper

- pySDC/core/Level.py
- pySDC/helpers/pysdc_helper.py
- pySDC/implementations/convergence_controller_classes/estimate_extrapolation_error.py
- pySDC/projects/Resilience/accuracy_check.py
- pySDC/projects/Resilience/advection.py
- pySDC/projects/Resilience/fault_stats.py
- pySDC/projects/Resilience/piline.py
- pySDC/projects/Resilience/vdp.py
The hooks become slightly more convoluted because I use the same hook class for different configurations of convergence controllers, such that the values I want to record don't necessarily exist.
I could implement a `get` function in the frozen class, which wraps `__dict__.get` in order to streamline this a bit. What do you think?
> Moved variable for extrapolated error estimate from level to convergence controller

- pySDC/core/Controller.py
- pySDC/implementations/controller_classes/controller_MPI.py
- pySDC/implementations/controller_classes/controller_nonMPI.py
- pySDC/implementations/convergence_controller_classes/adaptivity.py
- pySDC/implementations/convergence_controller_classes/basic_restarting.py
- pySDC/implementations/convergence_controller_classes/estimate_embedded_error.py
to reduce the mess of nonMPI and MPI versions a bit, I implemented these classmethods to get the correct implementation from the parent class of the two implementations for some convergence controllers.
Also, you can set a custom amount of max. restarts in the description now. This is needed because the restart convergence controller is loaded by default and this seemed the easiest way to pass parameters to it.
> Changed imports a bit

- pySDC/implementations/convergence_controller_classes/step_size_limiter.py
- pySDC/projects/Resilience/vdp.py
This is tested in the MPI implementation only, so the coverage might not show up. The implementation of the actual limiter is independent of MPI, however, such that otherwise it doesn't really matter which controller we use.
Closes #221
> Added test for the step size limiter

- .github/workflows/ci_pipeline.yml
- pySDC/core/Controller.py
- pySDC/core/Hooks.py
- pySDC/implementations/controller_classes/controller_MPI.py
- pySDC/implementations/controller_classes/controller_nonMPI.py
- pySDC/implementations/convergence_controller_classes/adaptivity.py
- pySDC/implementations/convergence_controller_classes/check_convergence.py
- pySDC/implementations/convergence_controller_classes/estimate_embedded_error.py
- pySDC/implementations/convergence_controller_classes/estimate_extrapolation_error.py
- pySDC/implementations/hooks/default_hook.py
- pySDC/implementations/hooks/log_embedded_error_estimate.py
- pySDC/implementations/hooks/log_extrapolated_error_estimate.py
- pySDC/implementations/hooks/log_solution.py
- pySDC/implementations/hooks/log_step_size.py
- pySDC/projects/PinTSimE/switch_estimator.py
- pySDC/projects/Resilience/accuracy_check.py
- pySDC/projects/Resilience/advection.py
- pySDC/projects/Resilience/heat.py
- pySDC/projects/Resilience/hook.py
- pySDC/projects/Resilience/piline.py
- pySDC/projects/Resilience/vdp.py
- pySDC/projects/matrixPFASST/controller_matrix_nonMPI.py
You can now add hooks either as a single hook, so the API is backwards compatible, or as an array of hooks. All hooks will be called one after another in the order that they are added whenever previously a single hook was called. The order should not matter since the hooks are not supposed to modify anything.
I wrote a few hooks that record small pieces of data that is interesting when using a certain convergence controller, which are added automagically when the respective convergence controller is added. For instance after each step, the step size is recorded as 'dt' when using adaptivity and so on.
Since the hooks have no access to the controller, I left the `__stats` variable in the hooks and merge them after the fact in the controller.
Since I need the `__num_restarts` variable for …
> Multiple Hooks simultaneously 

- docs/contrib/02_continuous_integration.md
> Added coverage details on contribution guidelines

- pySDC/core/Problem.py
- pySDC/implementations/problem_classes/AllenCahn_2D_FFT.py
- pySDC/implementations/problem_classes/Lorenz.py
- pySDC/implementations/problem_classes/Van_der_Pol_implicit.py
- pySDC/tests/test_problem.py
This is tested for Lorenz and van der Pol equations, but not for the Allen-Cahn equation. Instead, I actually wrote a unit test that creates a dummy instance of the problem class and let's it solve a series of randomised Dahlquist problems that look like a PDE. This makes sure that the reshaping that is required to solve PDEs with scipy works.
I test 3D, 2D and 0D problems this way.
Since the code specific to Allen-Cahn is not very much and complicated, I chose to forgo this test to not make the tests overly long.
Let me now if you disagree with my choices.
> Moved scipy reference solution function to core problem module

- pySDC/implementations/sweeper_classes/Runge_Kutta.py
- pySDC/tests/test_Runge_Kutta_sweeper.py
Taken from [here](https://doi.org/10.1007/BF01934920). The tests make sure that the embedded error estimate obtained with this method is order 4 and that the method is A-stable (within the patch of the complex plane that is tested).
> Added A-stable DIRK34 method

- pySDC/core/Problem.py
- pySDC/implementations/hooks/log_work.py
- pySDC/implementations/problem_classes/LeakySuperconductor.py
- pySDC/implementations/problem_classes/Lorenz.py
- pySDC/implementations/problem_classes/Van_der_Pol_implicit.py
- pySDC/projects/Resilience/fault_stats.py
- pySDC/projects/Resilience/hook.py
- pySDC/projects/Resilience/leaky_superconductor.py
I put in a counter class which can be passed to scipy solvers like gmres to count iterations, but you can also use it to count all sorts of things like Newton iterations and right hand side evaluations. This is useful because it is much more finely grained than SDC iterations for measuring the cost of the scheme.
There is also a hook that logs the increment in all counters in every step.
I did it this way because the problems are not supposed to interface with the hooks, but you can access problem attributes from the hooks.
I also implemented GMRES into the fully implicit version of the quench problem. However, to make it converge, I had to apply a preconditioner which is the linear part of the problem I want to solve with the Newton solver a.k.a. the diffusion part. Since the IMEX …
> Counters for measuring work

- pySDC/core/Controller.py
- pySDC/core/ConvergenceController.py
- pySDC/core/Sweeper.py
- pySDC/helpers/plot_helper.py
- pySDC/implementations/controller_classes/controller_MPI.py
- pySDC/implementations/controller_classes/controller_nonMPI.py
- pySDC/implementations/convergence_controller_classes/adaptivity.py
- pySDC/implementations/convergence_controller_classes/check_convergence.py
- pySDC/implementations/convergence_controller_classes/estimate_contraction_factor.py
- pySDC/implementations/convergence_controller_classes/hotrod.py
- pySDC/implementations/convergence_controller_classes/interpolate_between_restarts.py
- pySDC/projects/Resilience/leaky_superconductor.py
- pySDC/projects/Resilience/paper_plots.py
- pySDC/projects/Resilience/vdp.py
- pySDC/tests/test_convergence_controllers/test_InterpolateBetweenRestarts.py
New convergence controller which interpolates after a restart. There is a test that makes sure that the residual after solving the step for the second time is smaller than without interpolation and that that the interpolated value shows up the next step.
Also, since the non-MPI and MPI controllers deal with the steps differently (`controller.MS` and `controller.S`), I need some controller specific behaviour in the convergence controllers. Since I got tired of importing some controller and type-checking, I added a variable to both the controller as well as the convergence controllers that store if MPI is used or not.
> Interpolate after restarts

- pySDC/implementations/convergence_controller_classes/estimate_embedded_error.py
- pySDC/implementations/hooks/log_embedded_error_estimate.py
- pySDC/projects/Resilience/collocation_adaptivity.py
This is step 2 out of 3 for adaptivity based on different collocation problems. We already had the switch between quadrature rules between iterations and this convergence controller basically records the solution when after collocation problem is converged and before it is exchanged for the next one.
I just integrated the tests for this in the tests of the convergence controller that switches the quadrature rule.
The plot below shows the error estimate compared to the local error wrt a reference solution for an advection problem and they agree really well and have the correct order, which is what the test confirms.
In the left panel the type of the nodes is changed, in the middle panel the number of nodes is gradually increased and in the right panel the number of nodes is decreased. In …
> Estimate embedded error using different collocation problems

- pySDC/core/Problem.py
- pySDC/implementations/problem_classes/LeakySuperconductor.py
- pySDC/projects/Resilience/leaky_superconductor.py
- pySDC/tests/test_convergence_controllers/test_InterpolateBetweenRestarts.py
- pySDC/tests/test_projects/test_resilience/test_leaky_superconductor.py
Turns out I have been very stupid. The reason that scipy wouldn't give me a reference solution in time was because the problem is so stiff that RK45 is not a good method to solve the problem. But `scipy.solve_ivp` can also do implicit time stepping with a "BDF" scheme. This seems to work reasonably well to produce reference solutions rather fast. At least the error is decreased when I increase the accuracy requirements of SDC. I failed to show any sort of order, but I don't know if the reference solution is bad or if the problem is nasty. At least I can get errors down to machine precision with the reference solution, so I thought it's probably fine.
Also, I implemented an exponential transition term in the leak. However, it doesn't lead to faster heat up than the linear part because it …
> Reference solution for Quench problem

- pySDC/implementations/convergence_controller_classes/adaptive_collocation.py
- pySDC/implementations/convergence_controller_classes/adaptivity.py
- pySDC/implementations/convergence_controller_classes/estimate_embedded_error.py
- pySDC/projects/Resilience/collocation_adaptivity.py
- pySDC/projects/Resilience/vdp.py
- pySDC/tests/test_projects/test_resilience/test_adaptive_collocation.py
I apologise for the title.
This PR includes implementation for adaptivity using the error estimate from a few days ago.
There is a test running this with van der Pol which makes sure that the error threshold is not exceeded and also that the minimum error is no less than a tenth of the threshold. So this somewhat works now.
It remains to be seen what is the best configuration for running this. Should the order of the collocation problems increase or decrease? Do we care by how much we change the order? I.e. should we change the type of nodes or the number?
I have no idea as of now, but I am working on performance plots in other branches, which is why I would like to merge this now and do the analysis later as I go along with the paper, which I am spending 90% of my time on.
> Adaptivity based on error estimate based on interpolating between quadrature rules based on Thibaut

- pySDC/projects/Resilience/extrapolation_within_Q.py
- pySDC/tests/test_projects/test_resilience/test_extrapolated_error_within_Q.py
I was excluding the test for the local error of the solution of the collocation problem because for advection I found it to be one order lower than expected. Later, I remembered this is because for advection, we have an analytic solution. That means when I use the hook for computing the local error, I am really computing the global error, which is one order less. So I tricked myself... Not a good sign...
Anyways, I now solve not to a specified time, but to a specified number of time steps, which gives me the local error again, which is of the expected order, and the tests assert this now.
This comes with the benefit of being faster as well.
So no functionality changes in the tiny PR, just a small fix for my stupidity which slightly improves the tests.
> Improved tests for error estimate of Q

- pySDC/implementations/convergence_controller_classes/adaptivity.py
- pySDC/implementations/sweeper_classes/Runge_Kutta.py
- pySDC/tests/test_Runge_Kutta_sweeper.py
Previously you had to supply that manually, which was stupid. That's all that changed in this PR functionality wise.
Because of the aforementioned CI nonsense, I had to put all tests inside a function where I can do the imports. This is not the most pretty thing because then you can't easily see which test exactly failed, but this is a lazy approach that works...
> Embedded RK sweeper classes now contain the update order

- pySDC/implementations/convergence_controller_classes/adaptive_collocation.py
- pySDC/implementations/convergence_controller_classes/adaptivity.py
- pySDC/implementations/convergence_controller_classes/check_convergence.py
- pySDC/implementations/convergence_controller_classes/estimate_contraction_factor.py
- pySDC/implementations/convergence_controller_classes/estimate_embedded_error.py
- pySDC/implementations/convergence_controller_classes/hotrod.py
- pySDC/projects/Resilience/accuracy_check.py
- pySDC/projects/Resilience/collocation_adaptivity.py
- pySDC/projects/Resilience/piline.py
- pySDC/tests/test_Runge_Kutta_sweeper.py
This turns out to be more efficient for adaptivity.
Also when continuing to iterate instead of restarting, we make sure not to over-resolve the collocation problem now.
> Embedded error for multiple steps is no longer linearized by default

- pySDC/tests/test_Runge_Kutta_sweeper.py
The macOS runners in the CI were not happy with this, but now it seems to work again.
> Tried removing the `plt.show()` statement

- .github/workflows/ci_pipeline.yml
- pySDC/projects/compression/Docker/Dockerfile
- pySDC/projects/compression/Docker/docker_entrypoint.sh
- pySDC/projects/compression/Docker/install_pySDC.sh
- pySDC/projects/compression/Readme.rst
- pySDC/projects/compression/compression_convergence_controller.py
- pySDC/projects/compression/order.py
- pySDC/tests/test_projects/test_compression/test_proof_of_concept.py
- pyproject.toml
This PR includes a Dockerfile to create an image that contains a spack installed version of libpressio with python and SZ3 support that is ready for use with pySDC. Also, it contains a Readme showing how to build the image and use it to run locally. 
It contains a project for compression which contains the proof of concept I showed earlier, showcasing the order of accuracy in time is the same, no matter the compression error bound (within reason of course).
We can add files to this project in Clemson to do some actually useful things with compression (hopefully).
The CI pipeline now tests all tests marked with `libpressio` inside the container, which is on docker hub.
It also builds a coverage report and uploads it as an artefact to the same place that the other tests do. I called it …
> Initialised a project for compression using the libpressio library and added CI pipeline for testing

- pySDC/core/ConvergenceController.py
- pySDC/implementations/controller_classes/controller_MPI.py
- pySDC/implementations/controller_classes/controller_nonMPI.py
- pySDC/implementations/convergence_controller_classes/basic_restarting.py
- pySDC/implementations/convergence_controller_classes/estimate_extrapolation_error.py
- pySDC/implementations/convergence_controller_classes/spread_step_sizes.py
- pySDC/projects/PinTSimE/switch_estimator.py
I now pass the active steps as a keyword argument to the functions of the convergence controllers to allow "communication". This allows to streamline the nonMPI and MPI versions a bit. There is no functionality change here.
> Small cleanup in convergence controllers

- README.md
- docs/contrib/02_continuous_integration.md
The pre-commit hook I added will run black on all staged files and then add them to git again. Then, it will run flakeheaven and abort the commit if it finds any issues. 
You may consider this very annoying and intrusive. I find it less annoying then getting tons of emails because the linting action failed again.
If you don't like it, feel free to just close the PR without merging, but I personally find the hook quite useful.
> Added pre-commit hook to contribution guidelines for automating linting

- docs/contrib/02_continuous_integration.md
I apologise for the spam! But I was not totally satisfied with aborting the commit every time flakeheaven failed and I realised I can do better.
So now, if you add the git hooks and flakeheaven detects any issues, you can see them in the comments in the commit message which show you what you are committing. Now you can manually abort, or just not care.
You may also choose only to use the flakeheaven hook, which will not touch any files automatically, but reminds you that what you are committing will not pass the lint action.
> Split the pre-commit hook in two, such that flakeheaven now shows up as a comment in the commit message instead of aborting the commit

- pySDC/implementations/convergence_controller_classes/spread_step_sizes.py
- pySDC/implementations/hooks/log_work.py
- pySDC/tests/test_hooks/test_log_work.py
The hook records the increment in work counters. However, when doing this in the nonMPI controller with multiple steps, you need to separate the counters for the different "processes". I forgot this because in MPI it is naturally separated and in single step SDC there is also no problem. I wrote a pretty comprehensive test now that checks if the result is actually correct for both MPI and nonMPI versions.
> Fix for the `LogWork` hook

- pySDC/implementations/convergence_controller_classes/estimate_embedded_error.py
- pySDC/implementations/convergence_controller_classes/estimate_extrapolation_error.py
- pySDC/implementations/hooks/log_errors.py
- pySDC/implementations/problem_classes/TestEquation_0D.py
- pySDC/tests/test_convergence_controllers/test_error_convergence_controllers.py
TEST TEST TEST TEST TEST TEST TEST
I noticed an error in one of the implementations of the extrapolation error, so naturally I wrote some tests.
This PR includes a fix for the error and some tests for the error estimates. In a different test, I test that their order is correct, but here I test that the magnitude is comparable to the true error.
It shows that different error estimates perform differently, with the one comparing the solutions of two different collocation problems performing the best for this particular setup.
> More tests for error estimates and a fix for extrapolation error

- .github/workflows/ci_pipeline.yml
When running some actions, there is a warning that our CI is deprecated and will no longer work in the near future.
There is a [migration guide](https://github.com/mamba-org/provision-with-micromamba#migration-to-setup-micromamba) which I followed to update to the new version. I did not check that the post_processing action works, so maybe glance over the migration guide before merging.
> Migrating to new mamba action

- .github/workflows/ci_pipeline.yml
- pySDC/projects/compression/Docker/Dockerfile
- pySDC/projects/compression/compression_convergence_controller.py
The new container includes options that @joncalhoun40 picked out and @sansriti-ranjan may use during her masters project.
There is a weird bug where numpy has no attribute "bool". Professional as we are, we fixed it by the very good line
```
np.bool = np.bool_
```
This only showed up with the additional options for libpressio. Let's not worry about this.
> Added other compressors to the Libpressio container

- pySDC/implementations/problem_classes/Battery.py
- pySDC/implementations/problem_classes/BuckConverter.py
- pySDC/implementations/problem_classes/Piline.py
- pySDC/projects/PinTSimE/battery_model.py
- pySDC/projects/PinTSimE/buck_model.py
- pySDC/projects/PinTSimE/piline_model.py
The problem classes of the PinTSimE project now has also default parameters. In the battery classes I have to set V_ref and C equal to None and they were initialised as a numpy array afterwards, because flake raises an error when I set both values to a numpy array. 
Furthermore, there is a very small correction of docu of battery classes since I did a typo last time..
> Default parameters for PinTSimE problem classes + small docu correction

- .github/workflows/ci_pipeline.yml
I had the same issue with the libpressio container. I think that the last thing (coverage combine) in the step is successful and hence the entire action is marked as successful. Maybe this changed when we updated to the new mamba stuff. Anyways, in the macOS tests, there is no coverage step, so pytest is the last thing that is done in the step already and this was working fine.
Now, pytest is the last thing in its own step and then there is a separate step for the coverage report. Basically the same as for the libpressio container.
Is it really the issue that pytest was not the last command in its step? No idea, just guessing... But I made a fake test to confirm that the action fails when one test fails now.
> Split coverage and test actions because the GitHub action would not be marked as failed correctly

- pySDC/projects/DAE/sweepers/fully_implicit_DAE.py
- pySDC/tests/test_projects/test_DAE/test_sweeper.py
Lobatto and also Radau-left nodes lead to an incorrect solution. In case of a DAE, in each step also an initial condition for the derivative of the solution `du[0]` has to be computed. I will do this in the near future, but for now a warning is added to point out to the user.
I also adapted the test for this sweeper. Does this new test make sense? I hope yes, otherwise please let me know.
> Warning for fully_implicit_DAE sweeper

- pySDC/tests/test_problem.py
After @brownbaerchen noticed a warning was induced and test ignored, here is a solution that avoid that this part in the `base` test make `fenics` test fail (long story short, clashes between mpi4py imports ...)
> Fix some tests ignored by pyTest

- pySDC/implementations/sweeper_classes/Runge_Kutta.py
- pySDC/projects/Resilience/accuracy_check.py
- pySDC/tests/test_Runge_Kutta_sweeper.py
This PR includes two small changes to RK implementations.
First, @ikrom96git noticed that when supplying a residual tolerance larger than 0, the RK sweepers would do nothing and don't tell you about it. This is now fixed by setting the residual tolerance to -1 in the setter for the level as well as raising a warning when this is done.
Because RK methods are direct with a single iteration, the residual drops to machine precision after the first iteration. We can compute this to confirm that the method does what it's supposed to, but this is very computationally expensive and could dominate the computational time for explicit methods. So the residual is usually never computed and set to 0 instead.
The second change is regarding tests. The same things are testet as before (although I removed …
> Small tweaks for RK sweepers

- pySDC/implementations/problem_classes/TestEquation_0D.py
- pySDC/implementations/sweeper_classes/Runge_Kutta.py
- pySDC/tests/test_Runge_Kutta_sweeper.py
@ikrom96git noticed that RK sweepers were performing more RHS evaluations than necessary.
Namely, the `predict` function was inherited from the core Sweeper module and evaluated the RHS at the initial conditions.
However, in a similar fashion to the other sweepers, we add always 0 to the nodes and the right hand side evaluation there is never used.
Since the weights are stored as just another explicit stage in this implementation, we add another node for the right boundary (or two in the case of embedded methods). While we used to evaluate the right hand side at the solution(s), this is rarely needed.
When computing the extrapolated error estimate, I rely on the right hand side evaluations of the solutions, but in general, we can forgo this.
So in this PR all unnecessary right hand side …
> More efficient RK sweepers

- docs/contrib/02_continuous_integration.md
I don't know if anybody apart form me actually uses these git hooks, but if we make them public, I want them to work. I noticed only now that black fails when you give it a path that doesn't exist. (The same is not true for flakeheaven) Since deleting a file in git will stage it, but its path no longer exists, this hook will prevent you from committing deleted files. So I fixed it in a not so pretty way because I am bad at bash. If you have a better idea, feel free to suggest something.
> Fix failing pre-commit hook when deleting files

- pySDC/implementations/problem_classes/AcousticAdvection_1D_FD_imex.py
- pySDC/implementations/problem_classes/AllenCahn_1D_FD.py
- pySDC/implementations/problem_classes/AllenCahn_2D_FD.py
- pySDC/implementations/problem_classes/AllenCahn_2D_FD_gpu.py
- pySDC/implementations/problem_classes/AllenCahn_2D_FFT.py
- pySDC/implementations/problem_classes/AllenCahn_2D_FFT_gpu.py
- pySDC/implementations/problem_classes/AllenCahn_MPIFFT.py
- pySDC/implementations/problem_classes/AllenCahn_Temp_MPIFFT.py
- pySDC/implementations/problem_classes/Boussinesq_2D_FD_imex.py
- pySDC/implementations/problem_classes/FermiPastaUlamTsingou.py
- pySDC/implementations/problem_classes/GeneralizedFisher_1D_FD_implicit.py
- pySDC/implementations/problem_classes/GrayScott_1D_FEniCS_implicit.py
- pySDC/implementations/problem_classes/GrayScott_MPIFFT.py
- pySDC/implementations/problem_classes/HarmonicOscillator.py
- pySDC/implementations/problem_classes/HeatEquation_1D_FEniCS_matrix_forced.py
- pySDC/implementations/problem_classes/HeatEquation_1D_FEniCS_weak_forced.py
- pySDC/implementations/problem_classes/HeatEquation_ND_FD_CuPy.py
- pySDC/implementations/problem_classes/NonlinearSchroedinger_MPIFFT.py
- pySDC/implementations/problem_classes/TestEquation_0D.py
- pySDC/implementations/problem_classes/Van_der_Pol_implicit.py
- pySDC/implementations/problem_classes/VorticityVelocity_2D_FEniCS_periodic.py
For most of the problem classes I added default parameters (except for the classes using PETSc and `penningtrap`) (#206). Since flakebaerchen (sound similar to @brownbaerchen :D) has compliants like
```
Do not use mutable data structures for argument defaults.  They are created during function definition time. All calls to the function reuse this one instance of that data structure, persisting changes between them. [flake8-bugbear]
``` 
when I add something like
```
def __init__(self, nvars=[(256, 256)])
```
Hence, I set such parameters to None and set it inside the `__init__` function. 
I also found the Boussinesq equations in your fast-wave slow-wave publication, so I added docu for that problem. One problem less to document.
Let's see what pytest says..
> Default paramaters for most problem classes + docu for Boussinesq

- pySDC/implementations/sweeper_classes/Multistep.py
- pySDC/tests/test_Multistep_sweeper.py
As discussed in #327, you can abuse the sweeper class to do multistep methods.
I ended up doing this differently from what I initially thought and I don't know if this can be extended to arbitrary multistep methods.
In particular, at the moment it is required to use a fixed step size and restarts will probably also mess everything up.
I thought I start with a simple implementation of the most basic things and anybody is welcome to improve on this.
@lisawim, maybe we can discuss how we get the methods you want into this notation? I don't know exactly what you did with multistep methods so far.
I implemented methods with at most 2 steps, so not overly exciting, but for this I didn't have any issues with generating starting values, as they can be one order below the scheme.
I test the order …
> Added multistep methods as a sweeper

- pySDC/implementations/problem_classes/AdvectionEquation_ND_FD.py
- pySDC/implementations/problem_classes/HeatEquation_ND_FD.py
- pySDC/implementations/problem_classes/NonlinearSchroedinger_MPIFFT.py
There is a hook in the implementations that records the local error by generating exact solutions starting from the initial conditions and initial time of the step. However, many problems have an interface that is compatible with the hook, but always compute the exact solution from $t=0$, for instance when an analytic exact solution is available.
I added some warnings when this happens. It's not perfect, but it's better than nothing. If I forgot any problems, feel free to add the warnings yourself or tell me about it and I can do it.
> Added warnings when trying to compute local error with analytic exact solution

- pySDC/core/Problem.py
- pySDC/core/Sweeper.py
- pySDC/implementations/problem_classes/NonlinearSchroedinger_MPIFFT.py
- pySDC/implementations/problem_classes/Quench.py
- pySDC/projects/Resilience/Schroedinger.py
- pySDC/tests/test_problems/test_NonlinearSchroedinger_MPIFFT.py
Simple fully implicit version of nonlinear Schrödinger based on a `scipy` Jacobian-free Newton-Krylov solver. There is a test that this version does more or less the same as the IMEX version.
There is also a small change to the sweeper class which allows to use an explicit preconditioner for `QI`. This will warn you that you are doing something which is sort of stupid. But I find it useful for quick testing. That is to say when I want to use an explicit preconditioner, I can continue to use the implicit sweepers. If you don't like it, we can remove it.
> Fully implicit nonlinear Schrödinger

- pySDC/core/Hooks.py
- pySDC/core/Sweeper.py
- pySDC/helpers/stats_helper.py
- pySDC/implementations/hooks/default_hook.py
- pySDC/implementations/hooks/log_embedded_error_estimate.py
- pySDC/implementations/hooks/log_errors.py
- pySDC/implementations/hooks/log_extrapolated_error_estimate.py
- pySDC/implementations/hooks/log_restarts.py
- pySDC/implementations/hooks/log_work.py
- pySDC/implementations/sweeper_classes/generic_implicit_MPI.py
- pySDC/projects/Resilience/hook.py
- pySDC/tests/test_hooks/test_entry_class.py
The meta data was not sufficient for multiple processes in the sweeper. I added this, but also it is now customisable, as the test shows. The implementation seems a bit weird because the `Entry` class is outside of the class definition. This I had to do because otherwise I would get pickling errors when gathering stats across an MPI communicator in `filter_stats`.
While this more abstract interface is not necessarily more easy to deal with, you can, for instance, add another meta entry for a space rank or whatever might turn out useful in the future.
I neat side effect of this is that `type` and `iter` are only used as strings, so the python internal functions of the same name are not overwritten as before.
> More meta data in statistics

- pySDC/implementations/convergence_controller_classes/estimate_interpolation_error.py
- pySDC/tests/test_convergence_controllers/test_interpolation_error.py
The solution to the collocation problem is an order $M$ polynomial that we can evaluate wherever we want by means of interpolation. This is specific to SDC and hence I have to find it cool. 
If we use $M-1$ collocation nodes of a converged collocation problem with $M$ nodes, we get an order $M-1$ polynomial. The result is not the same as the solution to a colocation problem with $M-1$ nodes, but both are valid polynomial approximations of the solution of order $M-1$, only using different quadrature points. Equidistant nodes work, Radau points work, whatever. They just give different properties regarding stability and and accuracy of the end point. If we choose any $M-1$ points other than the end point, if possible, we give up the super convergence. But we don't need that.
We can instead …
> Error estimate based on interpolation inside the collocation problem

- pySDC/implementations/convergence_controller_classes/estimate_embedded_error.py
- pySDC/implementations/problem_classes/AcousticAdvection_1D_FD_imex.py
- pySDC/implementations/sweeper_classes/Runge_Kutta.py
- pySDC/tests/test_sweepers/test_Runge_Kutta_sweeper.py
We were recently wondering about high order IMEX RK and I found [this paper](https://arxiv.org/abs/2112.04167) that compares IMEX RK methods to IMEX SDC. I haven't read it fully. Just until they said they are aware of only [one 5th order IMEX RK method](https://doi.org/10.1016/S0168-9274(02)00138-1), which I then implemented.
Was a lot of fun because I couldn't copy the text directly from the pdf...
Anyways, this is actually four RK methods: diagonally implicit and explicit and order 4 and 5, so embedded as well as IMEX.
At least that's what they claim. In my testing the explicit methods are indeed order 4 and 5, but the implicit methods seem to be both order 5. Normally, I test the order of the embedded error estimate, but with this method, I get something around order 6 or nothing …
> IMEX RK5(4), with issues

- pySDC/implementations/sweeper_classes/Runge_Kutta.py
- pySDC/tests/test_sweepers/test_Runge_Kutta_sweeper.py
This one is newer and seems to be slightly better.
> Another IMEX RK embedded method of order 5(4)

- pySDC/core/Level.py
- pySDC/core/Problem.py
- pySDC/helpers/setup_helper.py
- pySDC/implementations/problem_classes/generic_ND_FD.py
- pySDC/tests/test_helpers/test_setup_helper.py
@tlunet rightfully remarked that the setup of a problem to run is not very inviting to new users. I have to admit, after 2 years of using pySDC, I still copy paste a description every time I need a new one. This PR is meant as a starting point to address this. It introduces a new function called `generate_description` and you can basically dump all variables in there and it will distribute them to the correct sub dictionaries for `step_params` and so on.
Also, there is a new interface for a default sweeper for a given problem. Most of the time, there is an obvious choice for a certain sweeper to use, but this needs to be implemented for each problem individually.
> Easier generation of description dictionaries

- pySDC/helpers/problem_helper.py
- pySDC/implementations/problem_classes/AllenCahn_1D_FD.py
- pySDC/implementations/problem_classes/AllenCahn_2D_FD.py
- pySDC/implementations/problem_classes/GeneralizedFisher_1D_FD_implicit.py
- pySDC/implementations/problem_classes/HeatEquation_ND_FD_CuPy.py
- pySDC/implementations/problem_classes/Quench.py
- pySDC/implementations/problem_classes/generic_ND_FD.py
- pySDC/projects/Resilience/quench.py
- pySDC/projects/Resilience/strategies.py
- pySDC/tests/test_helpers/test_problem_helper.py
I believe I had an error in the BCs for quench, so I tried to do it better. But I am very self conscious about this, so I would appreciate if somebody checked that this is actually correct.
So what I am doing to get Neumann BCs now?
- Generate FD matrix by putting the stencil on the diagonals
- Replace first and last line in the FD matrix with a one-sided stencil for the first derivative of the same order as the rest
- In the problem class: I have sth. like f(u) = Au + g(u), where A is the FD matrix and g is a nonlinear term. Here, I set the value for g at the first and last entry to the Neumann BC value (0 in this case)
- The grid has spacing dx = L / (N-1) and includes both boundaries
Does this make sense? I also don't know about the Dirichlet BCs, but I am not using them now...
If …
> Neumann BCs in problem helper

- pySDC/implementations/problem_classes/AllenCahn_1D_FD.py
- pySDC/tests/test_problems/test_AllenCahn_1D_FD.py
I added a test for the one-dimensional AllenCahn equation. The test is more or less based on `test_NonlinearSchroedinger_MPIFFT.py`, testing things like:
- Do right-hand side evaluations match in semi-implicit and fully-implicit case?,
- check errors for each problem classes,
- do number of function calls match in semi-implicit and fully-implicit case?,
- is `ProblemError` raised correctly when `nan` arises?,
- and are `logger.warning` also called correctly in case of `nan`
Such basic things. In my opinion there could be also tests for some problem specific things. But at this moment I don't know yet which things this could be. For example, one of the AC-classes uses *Finel's trick*, which is only a rewriting of the right-hand side. Here could be also a specific test added, but I don't …
> Test for `AllenCahn_1D_FD.py`

- pySDC/projects/DAE/misc/ProblemDAE.py
- pySDC/projects/DAE/problems/simple_DAE.py
- pySDC/projects/DAE/problems/synchronous_machine.py
- pySDC/projects/DAE/problems/transistor_amplifier.py
- pySDC/projects/DAE/sweepers/fully_implicit_DAE.py
Currently, the `fully_implicit_DAE` sweeper solves all DAE problems in the same way, i.e., using `scipy.optimize.root(f, x0, method='hybr')`. Since it could be useful to choose the solver problem dependent, a `solve_system` method is added to all DAE classes as this is already the case for all implemented ODE/PDE classes in `pySDC`. The implicit system is defined in the sweeper anyway, because this nonlinear system does not change (since it is the collocation problem to be solved).
So no magic here in this PR, I only moved these two line
```
opt = root(impl_sys, u0, method='hybr', tol=self.newton_tol)
me[:] = opt.x
```
Now, the problem classes still uses the same solver, but for the future, also different solver could be implemented and no one has to take care to change the sweeper itself …
> Added `solve_system` to all DAE problem classes

- pySDC/implementations/problem_classes/TestEquation_0D.py
- pySDC/implementations/sweeper_classes/generic_implicit_MPI.py
- pySDC/implementations/sweeper_classes/imex_1st_order_MPI.py
- pySDC/tests/test_sweepers/test_MPI_sweeper.py
Added MPI version of `imex_1st_order`. Accompanied by a simple test that runs a quick problem and checks if the result is the same, both in terms of `level.uend` as well as the residual. It's not the most elegant test, but the best compromise between kinda meaningful and quick to implement that I could come up with this morning.
> MPI version of IMEX sweeper

- pySDC/projects/Resilience/strategies.py
- pySDC/projects/Resilience/work_precision.py
Most impactful PR in the history of ever. The implications are akin to those associated with the creation of fire.
> Added some hyphens in plots

- pySDC/implementations/sweeper_classes/Runge_Kutta.py
One of the biggest PRs ever seen in ``pySDC``. Node for implicit Euler is changed. Since it is an implicit method it needs to be changed to 1.
> Fix for RK sweeper - Node changed for `BackwardEuler`

- pySDC/implementations/convergence_controller_classes/adaptivity.py
Normally, I like to abort iterating and restart the step whenever the residual grows when doing adaptivity with the polynomial based error estimate. However, when trying to implement adaptivity with both Abdel and Lisa's stuff, this turned out to be annoying. So this small PR makes this optional.
> Made aborting the step at growing residual optional in adaptivity

- pySDC/implementations/problem_classes/AllenCahn_MPIFFT.py
- pySDC/implementations/problem_classes/Brusselator.py
- pySDC/implementations/problem_classes/NonlinearSchroedinger_MPIFFT.py
- pySDC/implementations/problem_classes/generic_MPIFFT_Laplacian.py
- pySDC/tests/test_projects/test_AC/test_simple_forcing.py
Since the setup of the Laplacian using distributed FFTs is non-obvious and leads to a bunch of repeated code in various files, I want to setup base class for this. I have so far only ported two problem classes to this to make it easier for me to respond to feedback.
Importantly, this will allow me to port all classes derived from the base class to GPU, simply by changing the base class. I already include the `xp` class attribute for this. However, I stopped there because I need to pass NCCL as the communication backend to mpi4py-fft, which is not supported by the current API.
The plan is to merge this generic class into the main pySDC branch and then port to GPU in a separate branch that uses functionality of mpi4py-fft that is not out yet. If we get the CuPy tests to work, a possible …
> Generic MPI FFT class

- pySDC/implementations/problem_classes/AllenCahn_MPIFFT.py
- pySDC/implementations/problem_classes/GrayScott_MPIFFT.py
- pySDC/implementations/problem_classes/generic_MPIFFT_Laplacian.py
- pySDC/tests/test_problems/test_GrayScottMPIFFT.py
This PR includes a couple minor changes:
- Reversal of indices for $u$ and $v$ variables in Gray-Scott. AFAIK, they are now contiguous, which I recon gives better performance
- Gray-Scott inherits from generic MPI FFT class. I use this to port all classes that inherit from this to GPU simultaneously
- Test for Gray-Scott: The test is not perfect, but checks that the solvers are at least somewhat consistent. Previously, there were no tests at all.
- Minor fixes for Allen-Cahn
> Ported Gray-Scott to generic MPI FFT

- pySDC/playgrounds/DAE/DiscontinuousTestDAE.py
I added a very small file where the semi-explicit DAE ``DiscontinuousTestDAE`` is simulated using the new ``SemiImplicitDAE`` sweeper, which is for @Ouardghi to have a playground that should support his understanding how the new sweeper works. Since this file contains no special things (and thus there is no reason to add it to the project in my opinion..) I added the DAE playground for that.
> Playground for semi-explicit DAE ``DiscontinuousTestDAE`` using the new semi-implicit SDC-DAE sweeper

- pySDC/helpers/transfer_helper.py
- pySDC/implementations/convergence_controller_classes/check_iteration_estimator.py
- pySDC/implementations/datatype_classes/mesh.py
- pySDC/implementations/problem_classes/Brusselator.py
- pySDC/implementations/problem_classes/GrayScott_MPIFFT.py
- pySDC/implementations/sweeper_classes/imex_1st_order.py
- pySDC/implementations/transfer_classes/TransferMesh.py
- pySDC/implementations/transfer_classes/TransferMesh_FFT.py
- pySDC/implementations/transfer_classes/TransferMesh_MPIFFT.py
- pySDC/tests/test_transfer_classes/test_mesh_to_mesh.py
- pySDC/tests/test_transfer_classes/test_transfer_order.py
The transfer classes are poorly tested and are silently not compatible with some parts of the code.
#421 tracks some of these issues. This PR addresses a few. Namely, the new implementation of `imex_mesh` via `MultiComponentMesh` was causing some issues which I fixed in some transfer classes. I didn't check all. I added some tests to increase coverage and also reduced code duplication in some transfer classes.
I mainly need the transfer class for mpi4py-fft, which now does what I need. So I am not sure if I will continue working on fixing the transfer classes beyond this PR.
> Fixed some issues with transfer classes

- .github/workflows/gitlab_ci.yml
- .gitlab-ci.yml
- pySDC/tests/test_sweepers/test_MPI_sweeper.py
As I cannot push to master (which makes sense), this PR removes the cupy-test in gitlab, so that CI now succeeds again. Then failures can be detected easier.
Once, the cupy-tests are fixed, the updated code shall be merged in master and also the tests will be added again.
> Removed cupy-tests until they are fixed

- .gitlab-ci.yml
- pySDC/implementations/datatype_classes/cupy_mesh.py
- pySDC/implementations/problem_classes/generic_MPIFFT_Laplacian.py
- pySDC/implementations/transfer_classes/TransferMesh_MPIFFT.py
- pySDC/tests/test_datatypes/test_multicomponent_mesh.py
- pySDC/tests/test_transfer_classes/test_transfer_order.py
Because the GPU port of mpi4py-fft is still not merged and I don't see it happening anytime soon, I install my fork in the pipeline now. For some reason it didn't work when I put in the `prepare_juwels` job. Maybe someone knows what I did wrong  and has a suggestion such that it doesn't need to be reinstalled in the matrix job (which may be flaky again...).
This is not great, but without knowing what I am doing, I can't find a better solution...
This should be all that is needed to do very large space-time-time parallel PFASSTER runs on GPUs btw.
> Ported `IMEX_Laplacian_MPIFFT`, `fft_to_fft` and `MultiComponentMesh` to GPU

- pySDC/implementations/problem_classes/AllenCahn_2D_FD.py
- pySDC/projects/TOMS/AllenCahn_monitor.py
Very minor performance improvement, a first baby step towards streamlining Allen-Cahn implementations as mentioned in #434.
> Removed nested explicit loop in Allen Cahn 2D FD exact solution

- pySDC/core/ConvergenceController.py
- pySDC/core/Level.py
- pySDC/core/Step.py
- pySDC/helpers/pysdc_helper.py
- pySDC/implementations/convergence_controller_classes/basic_restarting.py
- pySDC/implementations/convergence_controller_classes/estimate_contraction_factor.py
- pySDC/implementations/convergence_controller_classes/estimate_embedded_error.py
- pySDC/implementations/convergence_controller_classes/estimate_extrapolation_error.py
- pySDC/implementations/convergence_controller_classes/estimate_polynomial_error.py
The idea behind `FrozenClass` is to allow to add and change only certain variables in order to prevent bugs from typos.
These are used in `status` objects, for instance. But we want to allow users to add status variables, without having a huge list of every variable anyone has ever used hardcoded in there.
In this PR, I fix a truly horribly BS solution that I implemented when I didn't know class attributes. I wrote a very complicated function that loops through all objects and bypasses the `__set_attr__` functions by using `__dict__`.
The new solution uses a class attribute for `FrozenClass` and derived classes, which carries a list of the allowed variables. This can easily be appended, of course, but it cannot be confused with simple assignment.
This should also give slightly better …
> Tweaks for `FrozenClass`

- pySDC/playgrounds/DAE/DiscontinuousTestDAE.py
- pySDC/playgrounds/DAE/playground_MPI.py
- pySDC/projects/DAE/README.rst
- pySDC/projects/DAE/environment.yml
- pySDC/projects/DAE/run/accuracy_check_MPI.py
- pySDC/projects/DAE/sweepers/SemiImplicitDAEMPI.py
- pySDC/projects/DAE/sweepers/fully_implicit_DAE.py
- pySDC/projects/DAE/sweepers/fully_implicit_DAE_MPI.py
- pySDC/projects/DAE/tests/test_MPI_sweepers.py
The current SDC-DAE sweepers now get MPI versions by adding ``fully_implicit_DAE_MPI`` and ``SemiImplicitDAEMPI`` to the SDC-DAE family! Hooray! For this, I implemented a base class for doing the MPI stuff called ``SweeperMPIDAE`` similar to the ``SweeperMPI`` base class. Then, for the SDC-DAE sweepers we have multiple inheritance again and it seems like it works, which is great.
To make sure the sweepers do work as they should I added a test that checks the order for both sweepers for different cases of DAEs (index one and index two case). I was struggling how to implement the test, because first I would like to write a test that checks if the MPI and non-MPI versions do match as [here](https://github.com/Parallel-in-Time/pySDC/blob/master/pySDC/tests/test_sweepers/test_MPI_sweeper.py) …
> SDC-DAE MPI Sweepers

- pySDC/implementations/problem_classes/Boussinesq_2D_FD_imex.py
Small bug that slipped through because the entire thing is untested.
> Fix for Boussinesq

- etc/environment-pytorch.yml
- pySDC/implementations/datatype_classes/mesh.py
- pySDC/playgrounds/ML_initial_guess/tensor.py
- pySDC/tests/test_datatypes/test_datatypes.py
While preparing for the NeuralPinT kickoff meeting, I thought we can trim the datatypes a lot by making the communicator a class attribute and do a nice `Tensor` datatype in this way.
Keep in mind that class attributes are shared between all instances of a class, but only across one task. That means we can assign different communicators to the class on different MPI processes and get essentially the same behaviour as before. I added a test to make sure this is actually the case.
Indeed, this allows to remove a lot of stuff from the datatypes.
Sadly, though, I noticed the problem with `Tensor` is the frequent cloning of tensors, which I was not able to remove right now. So I didn't solve the problem I set out to solve, but I still consider this better than before.
> Minor cleanup in datatypes

- pySDC/projects/DAE/tests/test_problems.py
The current test ``test_WSCC9_SDC_detection`` takes quite long time to run. When I wrote this test the intention was to prove the ``SwitchEstimator`` since at this time there was no test available. However, with #404 this has changed. The detection in this large power system is really expensive and testing this in the CI pipeline is probably not really necessary since
1. there are already some tests testing the dynamics of the power system in ``test_problems.py``,
2. in the PinTSimE project there is already a [file](https://github.com/Parallel-in-Time/pySDC/blob/master/pySDC/projects/PinTSimE/paper_PSCC2024/paper_plots.py#L153) where we investigated the behavior when the SE is applied to the power system, although only plots are studied.
Thus I decided to change the test by removing the …
> Speedup test for `WSCC9BusSystem`

- pySDC/projects/Resilience/venv/activate.sh
- pySDC/projects/Resilience/venv/config.sh
- pySDC/projects/Resilience/venv/modules.sh
- pySDC/projects/Resilience/venv/readme.md
- pySDC/projects/Resilience/venv/requirements.txt
- pySDC/projects/Resilience/venv/setup.sh
When running the code on the cluster, you want to use modules as much as possible because they are installed in an optimised way. Installing MPI with conda, for instance, will give significantly lower performance compared to MPI modules.
However, there is not a module for everything and so you have to install some custom stuff using pip. In Jülich there are quotas for the number of files you can have in ~/home, which is quickly exceeded when installing large packages like numpy.
The support team recommended to use python venvs instead, which can be stored wherever you want. There is a handy [template](https://gitlab.jsc.fz-juelich.de/kesselheim1/sc_venv_template/) for this that let's you choose you own modules and packages and then easily activate the venv by running `source activate.sh`. …
> Added venv infrastructure for running resilience project scripts on JUSUF

- pySDC/playgrounds/DAE/LinearTestDAEMinion.py
- pySDC/playgrounds/DAE/genericImplicitDAE.py
- pySDC/playgrounds/DAE/log_residual_components.py
- pySDC/playgrounds/DAE/residual_components.py
The $\varepsilon$-embedding can be used to derive reasonable schemes for (semi-explicit) DAEs that are close to stiff ODEs. When we consider a scalar problem of the form $$y'=f(y, z),$$ $$\varepsilon z' = g(y,z),$$ for $0 < \varepsilon \ll 1$, then setting $\varepsilon=0$ results in the semi-explicit DAE $$y'=f(y, z),$$ $$0 = g(y,z).$$ Thus, when SDC is applied to the ODE we get the scheme $$\mathbf{y}^{k+1} = \mathbf{y}_0 + \Delta t (\mathbf{Q}-\mathbf{Q}_d) f(\mathbf{y}^k,\mathbf{z}^k) + \Delta t \mathbf{Q}_d f(\mathbf{y}^{k+1},\mathbf{z}^{k+1}),$$ $$\varepsilon\mathbf{z}^{k+1} = \varepsilon\mathbf{z}_0 + \Delta t (\mathbf{Q}-\mathbf{Q}_d) g(\mathbf{y}^k,\mathbf{z}^k) + \Delta t \mathbf{Q}_d g(\mathbf{y}^{k+1},\mathbf{z}^{k+1}).$$ Again, setting $\varepsilon=0$ results in a first …
> Playground: Residual components in DAE case when using SDC-DAE sweeper arised from epsilon-embedding

- .gitlab-ci.yml
- etc/check_node_avail.sh
and exit before submitting a job to a partition where it cannot be picked up by any nodes.
The artifacts are still being tried to be collected (which fails because the files don't yet exist).
As the job fails if no node can run the SLURM-Job, the behaviour is similar to current behaviour, but with earlier failing of the CI-Job, as it does not need to time out.
Creating a warning instead of a failure is currently not possible due to an issue in the jacamar-runner (Issue is opened).
> Handle SLURM issues

- pySDC/projects/DAE/sweepers/RungeKuttaDAE.py
- pySDC/projects/DAE/tests/test_RungeKuttaDAE.py
Since `SwitchEstimator` requires values at the intermediate stages when applying Runge-Kutta methods, these values will now be computed in `update_nodes`. This required adding the `integrate` method. Here, we cannot inherit from the parent since it uses the `get_full_f` method (splitting of the right-hand side `f` which is currently not possible).
When adding that I noticed that `EDIRK4DAE` achieved order $3$ for a fully-implicit index- $2$ problem instead of $2$ as already set in the current test. I was wondering since order reduction could be expected for higher-index problems. However, when you compute the theoretically derived order conditions for index- $2$ problems in [[E. Hairer, C. Lubich, M. Roche, p. 63]](https://www.google.com/url?sa=t&source=web&rct=j&opi=89978449&url=https://l …
> Added `integrate` method to `RungeKuttaDAE`

- .github/workflows/gitlab_ci.yml
- .github/workflows/postprocess.yml
- CONTRIBUTING.md
Fixed typo in waiting for other pipeline and corrected issue with providing artifacts.
Now the website builds successfully (not uploaded, because this is done only from main branch).
Some tests were flaky for unknown reasons (failed in first go, but finished successfully in second approach)
> Fixed issue with waiting for other pipeline

- .github/workflows/postprocess.yml
Corrected name of branch used for comparing to decide on wether to upload the documentation.
Unclear, why it worked before with the previous syntax.
> Changed style of naming the default branch (when deciding on if to upload docs)

- pySDC/helpers/pysdc_helper.py
- pySDC/tests/test_helpers/test_frozen_class.py
In #437, I made the names the classes are allowed to have a class attribute of `FrozenClass`. Turns out there are a few issues.
Some convergence controllers added attributes in every step, leading to huge lists. This caused really poor performance. This PR includes a fix for that such that attributes are only ever added once, regardless of whether it is allowed or not.
However, since the allowed attributes are a class attribute of `FrozenClass` they are shared across all derived classes. And I didn't find a quick fix for that. It's not a huge problem. Basically, you add, for instance `error_embedded_estimate` to the status class of level and then you can set `error_embedded_estimate` for the status of the step as well. It's not nice. It doesn't really enforce what the frozen classes are …
> FrozenClass performance fix

- pySDC/implementations/controller_classes/controller_nonMPI.py
- pySDC/implementations/problem_classes/AllenCahn_2D_FFT.py
- pySDC/implementations/problem_classes/AllenCahn_MPIFFT.py
I fixed a few typos in Allen-Cahn problems. In the MPI version with forcing, some typos were bugs. Since the bugs only effect runs with a single processor, I don't think it matters too much. All other typos were in comments. Also, in the non-MPI version I removed some unnecessary copying and reshaping.
Also, there is a new version of mpi4py. If you now try to pickle a communicator, it will raise a `ValueError` for whatever reason. So we need to add this in the non-MPI controller step instantiation. This update must have been extremely recently because the actions this morning passed, but [this one](https://github.com/brownbaerchen/pySDC/actions/runs/10140130314/job/28034717724) in the meantime failed, in case you don't believe me ;).
> Small fixes

- .github/workflows/gitlab_ci.yml
Use a new version of Github2Lab-Action
This new version triggers a new Gitlab-Pipeline even if no new code is pushed. This makes it possible to rerun a Github-Action with rerunning Gitlab-CI. It also means that a scheduled pipeline now triggers a separate Gitlab-CI.
Furthermore start the Gitlab-Actions a minute apart to make sure the querying doesn't fail.
> Fix syncing ci

- pySDC/helpers/NCCL_communicator.py
- pySDC/helpers/plot_helper.py
- pySDC/implementations/problem_classes/AllenCahn_MPIFFT.py
- pySDC/implementations/problem_classes/NonlinearSchroedinger_MPIFFT.py
These are a few small changes I did when starting to run large GPU simulations. I will try and merge it back in reasonably sized chunks. Although there will be some more unpleasant PRs than this one in the future..
The changes to the NCCL communicator where needed so that only data that resides on the GPU is communicator using NCCL and MPI is used otherwise. Keep in mind that we still haven't figured out how to test in parallel on GPUs in the pipeline.
> Just a few small fixes

- pySDC/implementations/convergence_controller_classes/estimate_polynomial_error.py
- pySDC/implementations/datatype_classes/cupy_mesh.py
- pySDC/implementations/datatype_classes/mesh.py
- pySDC/implementations/problem_classes/polynomial_test_problem.py
- pySDC/tests/test_convergence_controllers/test_polynomial_error.py
Also, I applied the same cleanup as in #438 to the cupy mesh datatype.
> Ported polynomial based error estimate to GPU

- README.md
These instructions are especially useful if working in a `venv`. We had to come up with this approach in https://github.com/precice/tutorials/pull/557 to get pySDC installed & running with a single call of a script.
Using `venv` is recommended by newer `pip` versions to not interfere with the system python packages. E.g. for the `pip` version coming with Ubuntu 24.04.
On Ubuntu 24.04 I get:
```
$ pip --version
pip 24.0 from /usr/lib/python3/dist-packages/pip (python 3.12)
$ pip install --user pySDC
× This environment is externally managed
╰─> To install Python packages system-wide, try apt install
python3-xyz, where xyz is the package you are trying to
install.
If you wish to install a non-Debian-packaged Python package,
create a virtual environment using python3 -m venv path/to/venv. …
```
> Add installation instructions using `pip install git+...`

- .github/workflows/ci_pipeline.yml
- .github/workflows/postprocess.yml
- .gitlab-ci.yml
The coverage-file created in Gitlab was named without the "3.10" suffix. This lead to the issue, that it was not taken into account, when creating the whole coverage report.
This issue now solves this, but changing the name of the created coverage-file. An alternativ would be to remove the need for the suffix "3.10" in another file (`.github/workflows/postprocess.yml` line 36).
Then, the coverage-report should include the coverage information from the cupy-tests.
> Coverage-report now uses less restricted file-names

- .github/workflows/gitlab_ci.yml
Now the artifacts should be combined properly and provided together.
Previously only the artifacts from Github-Actions were uploaded and provided to e.g. coverage.io
Can (and should) be checked by looking at the named files that are uploaded. Those should include `coverage_cupy.dat` and `coverage_benchmkark.dat`.
> Added path to download artifacts from Gitlab-CI to

- .github/workflows/ci_pipeline.yml
- .github/workflows/gitlab_ci.yml
The coverage-reports from the Jobs in Gitlab-CI are now also transferred correctly and combined with the other reports.
> Coverage-reports from Gitlab are now found and combined

- pySDC/implementations/sweeper_classes/Runge_Kutta.py
- pySDC/projects/Resilience/strategies.py
- pySDC/tests/test_sweepers/test_Runge_Kutta_sweeper.py
Globally stiffly accurate DIRK are characterised by the last row of the Butcher tableau containing the weights. This means the last stage is the solution to the step. With the new implementation, the extra step for the combination of the weights is removed. Further, stages are only solved with implicit Euler if needed. This can be considered a bugfix, since before the same solution was computed with more work.
The reason I implemented this is that globally stiffly accurate DIRK methods are easy to use for simple DAEs. For instance, with RBC, in place of an equation for the pressure, there is the divergence-free constraint. If we then do a "collocation update" or it's equivalent in the DIRK context, we don't compute the pressure correctly. This is not case if we just use the last stage as …
> More efficient globally stiffly accurate DIRK

- pySDC/implementations/datatype_classes/cupy_mesh.py
Seems I was too eagerly deleting stuff in #469 ... sorry about that! It's a shame we can't get the GPU tests with multiple GPUs to work.
> Bugfix in computing absolute value with cupy datatype

- pySDC/implementations/convergence_controller_classes/adaptivity.py
- pySDC/implementations/convergence_controller_classes/step_size_limiter.py
- pySDC/tests/test_convergence_controllers/test_adaptivity.py
- pySDC/tests/test_convergence_controllers/test_step_size_limiter.py
This is useful, for instance, when caching matrix factorisations that can only be reused when the step size stays the same.
btw, what happened to the codecov bot?
> Added option to skip dt change if insignificant

- pySDC/implementations/datatype_classes/mesh.py
I got confused looking at the implementation of `__abs__` in mesh and just want to spare the next person reading it from the same confusion.
`numpy.amax` is just an alias for `numpy.max`. I was wondering what the `a` is doing and it's doing nothing. So I removed it. Also, taking the maximum between a positive or zero number and zero will be the first number, so that's just superfluous.
> Small cleanup in mesh datatype

- docs/contrib/02_continuous_integration.md
When flakeheaven doesn't find anything, it returns `0`. When ruff doesn't find anything it returns empty. The current git hook would therefore always print that ruff has failed in the commit message. This is just a fix so that the commit message is unaltered if there are no issues with the linter.
> Fixed prepare-commit-msg for ruff git hook

- pySDC/helpers/spectral_helper.py
We need to replace some lines in the matrix with the boundary conditions in tau methods. Then we also need to replace the respective values in the right hand side with the values at the boundary. This PR makes the second part more efficient. After profiling on GPUs, it turns out that the previous implementation was rather expensive. By caching a mask that can streamline this operation, solving systems with already factored matrices is up to 10x faster on GPUs and 2x faster on CPUs than before, depending on resolution.
> Increased performance of tau methods

- pySDC/implementations/problem_classes/RayleighBenard.py
After profiling the code on GPUs some more, I noticed some efficiency can be gained from reducing the number of matrix multiplications. That is all that I am doing here: Rather than computing derivatives by multiplying each component with the derivative matrix separately, I construct a large matrix containing the derivative matrix multiple times in order to compute all derivatives simultaneously. Also, I cache the $L$ matrix in the basis of Chebychov T polynomials, rather than computing it every time. This is not a huge difference, but saves a few ms in every call of the function on both CPU and GPU.
> More efficient `eval_f` in RBC on GPU

- pySDC/helpers/spectral_helper.py
The redistributions use alltoall communication and are expensive. By reducing these, I could see slightly better parallel efficiency in Rayleigh-Benard.
> Reduced the number of redistributions in spectral helper slightly

- pySDC/helpers/plot_helper.py
- pySDC/helpers/pysdc_helper.py
- pySDC/implementations/convergence_controller_classes/step_size_limiter.py
- pySDC/implementations/problem_classes/generic_spectral.py
- pySDC/implementations/sweeper_classes/Runge_Kutta.py
- pySDC/projects/Resilience/RBC.py
- pySDC/projects/Resilience/README.rst
- pySDC/projects/Resilience/fault_stats.py
- pySDC/projects/Resilience/paper_plots.py
- pySDC/projects/Resilience/strategies.py
- pySDC/projects/Resilience/tests/test_RBC.py
- pySDC/projects/Resilience/work_precision.py
- pySDC/tests/test_convergence_controllers/test_step_size_limiter.py
This PR includes a configuration for Rayleigh-Benard convection (RBC) on a 256x128 grid with Rayleigh number of $2^4$. Reference solutions are computed for t=20 and t=21. Individual runs for fault experiments then start at t=20 and go to t=21. There is a convergence controller that makes sure the target time is reached to accuracy of $10^{-9}$, which is sufficiently accurate to use the reference solution. I verified that I get the order of the collocation problem relative to such a reference solution, even if the residual stays at order 1 during the runs. The latest theory is that this is because the problem is perturbed by the method that enforces the boundary conditions. This perturbation is missing in the residual and I haven't found a good way to represent it there (yet). This matters …
> Resilience experiments with Rayleigh-Benard convection

- pySDC/helpers/spectral_helper.py
The main advantage of this is that the NCCL communicator will not synchronise the stream before Allreduce, which it will do before allreduce. So this increases performance on GPUs a little bit.
> Switched from allreduce to Allreduce in spectral helper

- pySDC/implementations/convergence_controller_classes/estimate_embedded_error.py
- pySDC/implementations/sweeper_classes/Runge_Kutta.py
- pySDC/implementations/sweeper_classes/Runge_Kutta_Nystrom.py
- pySDC/tests/test_sweepers/test_Runge_Kutta_sweeper.py
This PR includes a few things:
- Collocation matrix now includes only the Runge-Kutta matrix and no longer the weights for computing the solution at the end point
- `compute_end_point` now computes the solution at the end point. For stiffly accurate methods, the solution at the last node is copied
- IMEX RKM can now have different weights for explicit and implicit methods. This is crucial for stiffly accurate IMEX methods, which can be applied to DAEs. If only the implicit part is stiffly accurate, a collocation update is still needed.
- Added the second order stiffly accurate IMEX RK method (ARK2) that Dedalus use as well as IMEX Euler. The ARK2 method is the only one we have atm that works for DAEs like Rayleigh-Benard.
- Refactor for Runge-Kutta Nyström: This is still using the old …
> Refactor of RK implementation

- pySDC/core/convergence_controller.py
- pySDC/implementations/controller_classes/controller_MPI.py
- pySDC/implementations/controller_classes/controller_nonMPI.py
- pySDC/projects/GPU/configs/base_config.py
- pySDC/projects/GPU/run_experiment.py
- pySDC/projects/GPU/tests/test_configs.py
My laptop recently ran out of storage during a simple run in the GPU project because it regularly stores the stats. This PR changes the behaviour such that only the stats since the last save point are saved and merged together in the end.
> Small fix for GPU project

- pySDC/core/controller.py
- pySDC/implementations/hooks/default_hook.py
- pySDC/implementations/hooks/log_timings.py
I split off the timings from the default hook and implemented a version for GPU timings. This works with CUDA events, see the [CuPy documentation](https://docs.cupy.dev/en/stable/user_guide/performance.html) for details on how to measure GPU timings.
Note that the time elapsed on CPU is not in general correlated with the time to run an operation on GPU. There are some operations that implicitly synchronise device and host, such as memory transfers between the two, resulting in similar CPU and GPU timings in pySDC. I did not find a meaningful difference in average `timing_step` between the two hooks in my experiments. Still, I think we need a hook that makes this reliable by explicitly synchronising.
> Implemented hook for measuring GPU times

- pySDC/implementations/convergence_controller_classes/adaptivity.py
- pySDC/implementations/convergence_controller_classes/check_convergence.py
- pySDC/implementations/convergence_controller_classes/estimate_embedded_error.py
- pySDC/implementations/convergence_controller_classes/estimate_polynomial_error.py
This is needed for declaring convergence based on the increment when using the [polynomial based error estimate](https://github.com/Parallel-in-Time/pySDC/blob/master/pySDC/implementations/convergence_controller_classes/estimate_polynomial_error.py), which writes the error estimate to `level.status.error_embedded_estimate`, just like the increment based error estimate.
In $\Delta t$-$k$-adaptivity with RBC, I use a stopping criterion that uses both residual and increment, so I need both the error estimate and the increment.
This PR should be seen as a bugfix. Previous tests for `CheckConvergence` are still valid.
> Added `increment` to level status

- pySDC/helpers/NCCL_communicator.py
In this PR
- synchronisation is skipped for some MPI operations that are used in mpi4py-fft, such as `Is_inter`,
- synchronisation is skipped if `allreduce` and `reduce` (lower case) are used with data that is not on GPU,
- `Barrier` now synchronises the device to cause a barrier on device as well, rather than just on the host.
These changes are rather small and are still not captured by any test. There is some unrelated issue that causes some Allen-Cahn tests to fail. I haven't looked into why yet, but they also fail on the master branch.
> Added a few things to the NCCL communicator

- pySDC/implementations/problem_classes/GrayScott_MPIFFT.py
- pySDC/implementations/problem_classes/generic_MPIFFT_Laplacian.py
- pySDC/projects/GPU/configs/GS_configs.py
- pySDC/tests/test_problems/test_generic_MPIFFT.py
Turns out the generic mpi4py-fft Laplacian class was already 3D capable.
This PR includes three things
- minor refactor of generic mpi4py-fft Laplacian class
- tests for generic mpi4py-fft Laplacian class
- 3D initial conditions for Gray-Scott example
> 3d Gray-Scott

- pySDC/implementations/sweeper_classes/generic_implicit_MPI.py
- pySDC/implementations/sweeper_classes/imex_1st_order_MPI.py
I was surprised by how much more memory diagonal SDC needs compared to space-only parallelism. Unfortunately, I didn't find an easy solution. Instead, I just removed one unnecessary memory allocation.
In diagonal SDC, the solution and right hand side evaluation is stored at only one collocation node. But also the solution and RHS at the initial conditions is stored and every task stores the solution to the step.
Compared to space-only parallelism at the same number of overall tasks, all solution size objects are larger by the number of tasks in time.
If one uses four tasks in time / four colocation nodes, the solution and RHS evals in diagonal SDC take up $\frac{2\times 4}{5}=1.6$ times the memory compared to space-only parallelism each. And $u_\mathrm{end}$ is four times as large.
The …
> Tiny cleanup

- pySDC/implementations/problem_classes/RayleighBenard.py
- pySDC/tests/test_problems/test_RayleighBenard.py
This may be helpful when using ML initial guess. The initial guess should be better if it satisfies the Dirichlet BCs. This implementation is a bit expensive, but I am pretty sure I can remove the transforms from this if needed.
> Added separate function to apply Dirichlet BCs to any solution in RBC

- pySDC/implementations/convergence_controller_classes/check_convergence.py
Abdel and I were running into issues from time to time when the SDC residual of the prediction was low enough proclaim convergence. In this case, the code just does not do anything anymore but counting up the time and returning this solution.
I would consider this a bug.
The fix here is a bit weird because in single level SDC the sweep and iterations variables are interchangeable. Do you see any problem with doing it like this @pancetta?
> Perform at least one SDC iteration

- pySDC/projects/DAE/environment.yml
For whatever reason, a recent scipy update has led to slightly larger errors and failing tests. Limiting the version to below 1.15 fixes this issue.
> Limited SciPy version in DAE project

- .github/workflows/ci_pipeline.yml
- .gitignore
- pySDC/helpers/blocks.py
- pySDC/helpers/fieldsIO.py
- pySDC/tests/test_helpers/test_fieldsIO.py
A small issue I encountered, in my attempt to use pySDC generated data to train a ML model for Rayleigh Benard convection, is that there was no efficient options (that I knew of) to write many (many many) field solutions when running many space-parallel simulations, hence a "tiny" technical problem.
So I quickly implemented a `FieldsIO` generic (abstract) class to write multiple field solution into a binary file, and specialized it to scalar, 1D and 2D fields written on Cartesian grids. All are compatible with Numpy arrays, and each class is as generic as possible, such that most problem class using one or more `mesh` class for their state variable can use it.
Also, I added the MPI-IO functionalities to the 1D and 2D grid classes, that can be used with any type of Cartesian block …
> FieldsIO implementation for 0D to 2D cartesian grid fields, with MPI

- pySDC/helpers/fieldsIO.py
I had some trouble with round-off errors today and noticed that my numpy doesn't actually have quadruple precision. So `np.float128` will raise an error on my machine. `np.longdouble`, on the other hand, is just regular double on my machine. This is extremely weird behaviour that I neither like nor understand. I switched out the quadruple precision things for the word version so I can run the IO stuff with double precision at least.
Notice that the [numpy documentation](https://numpy.org/doc/2.1/reference/arrays.scalars.html#numpy.longdouble) says that `np.longdouble` is an alias for `np.float128` on Linux x86_64 machines. So this fix applies to Mac and Windows users.
> Fix for missing numpy data types on some platforms

- pySDC/implementations/convergence_controller_classes/adaptivity.py
- pySDC/implementations/convergence_controller_classes/estimate_embedded_error.py
- pySDC/implementations/convergence_controller_classes/estimate_polynomial_error.py
- pySDC/tests/test_convergence_controllers/test_polynomial_error.py
I should have done this long ago. For the Williamson 5 test case that simulates the Earth, the numbers are so huge, that you really need to look at relative errors. The tutorial for the Gusto coupling will use the Williamson 5 test case and with adaptive step size selection. However, I thought I would do a separate PR for all the non-Gusto related changes that are needed for that.
This PR includes a Firedrake-compatible version of dt-k-adaptivity. The interpolation was done in a NumPy specific way, which I want to keep because it is faster on NumPy and CuPy data than a more generic version. This Firedrake enabled version should actually work with any datatype, but we are not entirely sure if you need to invert the mass matrix during the interpolation. Currently I left in the FE/Firedrake …
> Implemented relative error estimates for adaptive step size selection

- .github/workflows/ci_pipeline.yml
- docs/source/tutorial/doc_step_7_E.rst
- docs/source/tutorial/doc_step_7_F.rst
- pySDC/helpers/pySDC_as_gusto_time_discretization.py
- pySDC/implementations/problem_classes/GenericGusto.py
- pySDC/tests/test_helpers/test_gusto_coupling.py
- pySDC/tests/test_tutorials/test_step_7.py
- pySDC/tutorial/step_7/F_2_plot_pySDC_with_Gusto_result.py
- pySDC/tutorial/step_7/F_pySDC_with_Gusto.py
- pySDC/tutorial/step_7/README.rst
This enables to use pySDC as a time discretisation method within Gusto, or to setup a geophysical problem in Gusto and then run it in pySDC.
The intended use is to take a script running a Gusto problem, setup the Gusto timestepper with the pySDC integrator and then either just use that in normal Gusto fashion, or extract the controller from the pySDC integrator and run in pySDC.
- helper that inherits from the Gusto base time discretisation and sets up a pySDC controller that can then be used on it's own or called from Gusto during the time stepping 
- generic Gusto problem class that accepts a Gusto equation or a Gusto residual and assembles nonlinear variational problems to be solved for evaluating the right hand side or doing an Euler step
- IMEX version of generic gusto problem class …
> Added coupling between pySDC and Gusto

- pySDC/core/space_transfer.py
- pySDC/implementations/transfer_classes/TransferFenicsMesh.py
- pySDC/implementations/transfer_classes/TransferMesh_NoCoarse.py
- pySDC/implementations/transfer_classes/TransferParticles_NoCoarse.py
> Minor refactor for space transfer classes

- pySDC/helpers/spectral_helper.py
- pySDC/implementations/problem_classes/RayleighBenard.py
- pySDC/implementations/problem_classes/generic_spectral.py
- pySDC/tests/test_problems/test_RayleighBenard.py
This PR includes some minor improvements to the RBC implementation. I have become lazy in merging back my development branch for some thesis results and this is the first step of many to correct that.
- Fixed typo in `Prandtl` in RBC
- Added a couple of solvers in the generic spectral problem
- Added cache for shapes to avoid some communication when doing dealiasing in spectral helper
> Fixed Rayleigh number definition in RBC

- pySDC/helpers/pySDC_as_gusto_time_discretization.py
- pySDC/implementations/problem_classes/HeatFiredrake.py
- pySDC/implementations/transfer_classes/TransferFiredrakeMesh.py
- pySDC/tests/test_helpers/test_gusto_coupling.py
- pySDC/tests/test_transfer_classes/test_firedrake_transfer.py
- pySDC/tests/test_tutorials/test_step_7.py
- pySDC/tutorial/step_7/E_pySDC_with_Firedrake.py
- pySDC/tutorial/step_7/F_pySDC_with_Gusto.py
This PR includes very rudimentary versions of multi-level SDC that work with both the Firedrake and the Gusto examples. I have not made an effort to find the best possible parameters on the different levels. I reckon this exceeds the scope of what I can do within the rest of the week. And, as mentioned below, some performance improvements are needed to really use this in practice.
Anyways, I wanted to do the PR already now so I can add block Gauß-Seidel SDC / PFASST to the Gusto coupling in the coming days, which may be more useful.
- Transfer class `MeshToMeshFiredrake` that transfers between any unrelated Firedrake meshes that are simultaneously supported by the `Firedrake.interpolate` method.
- Transfer class `MeshToMeshFiredrakeHierarchy` that transfers between meshes that have been …
> Added multi-level SDC for Firedrake and Gusto coupling

- pySDC/helpers/firedrake_ensemble_communicator.py
- pySDC/helpers/pySDC_as_gusto_time_discretization.py
- pySDC/implementations/datatype_classes/firedrake_mesh.py
- pySDC/tests/test_datatypes/test_firedrake_mesh.py
- pySDC/tests/test_helpers/test_gusto_coupling.py
- pySDC/tutorial/step_7/F_pySDC_with_Gusto.py
You can now select a number of time-steps that are solved concurrently when using pySDC as a Gusto time discretisation. Each step will then have a step size of $\Delta t / N$ with $N$ the number of steps and $\Delta t$ the step size of the Gusto time discretisation. Potentially, this may be used to parallelise solving of the transport part, @jshipton.
- Added communication functions to the Firedrake mesh datatype
- Added p2p communication to the Firedrake ensemble communicator wrapper
- Rescaled step size in the `pySDC_integrator`, which is the Gusto time discretiation
- Added support for MPI controller to `pySDC_integrator`
- Test that block Gauß-Seidel SDC with single node and single iteration gives the same result as just running implicit Euler
- MPI parallel version of the above test …
> Added multi-step SDC to the Gusto coupling

- pySDC/projects/Resilience/GS.py
- pySDC/projects/Resilience/Lorenz.py
- pySDC/projects/Resilience/RBC.py
- pySDC/projects/Resilience/README.rst
- pySDC/projects/Resilience/fault_stats.py
- pySDC/projects/Resilience/paper_plots.py
- pySDC/projects/Resilience/reachTendExactly.py
- pySDC/projects/Resilience/strategies.py
- pySDC/projects/Resilience/tests/test_ReachTendExactly.py
- pySDC/projects/Resilience/work_precision.py
This is a rather large PR that contains parameters for experiments and plotting stuff and no new features.
> Added plots for thesis on computational efficiency and resilience

- pySDC/implementations/problem_classes/GrayScott_MPIFFT.py
- pySDC/implementations/problem_classes/generic_MPIFFT_Laplacian.py
- pySDC/projects/GPU/README.rst
- pySDC/projects/GPU/analysis_scripts/3d_plot_GS_large.py
- pySDC/projects/GPU/analysis_scripts/large_simulations.py
- pySDC/projects/GPU/analysis_scripts/parallel_scaling.py
- pySDC/projects/GPU/analysis_scripts/plot_RBC_matrix.py
- pySDC/projects/GPU/analysis_scripts/plot_large_simulations.py
- pySDC/projects/GPU/configs/GS_configs.py
- pySDC/projects/GPU/configs/RBC_configs.py
- pySDC/projects/GPU/configs/base_config.py
- pySDC/projects/GPU/paper_plots.py
- pySDC/projects/GPU/run_experiment.py
Again, this is almost no features, but just loads of configs and plotting scripts. The only feature in sight is that I expanded the initial conditions for Gray-Scott to 3D blobs.
This is another large one, but it should be the last one of this kind for now.
> Added scripts for generating plots for chapters 7 and 8 in the thesis

- .github/workflows/ci_pipeline.yml
- pySDC/projects/GPU/paper_plots.py
- pySDC/projects/Resilience/AC.py
- pySDC/tests/test_convergence_controllers/test_adaptivity.py
The features from Gusto that we use here work again with the most recent Firedrake, so I switched the pipeline to use the latest Firedrake docker container. (@jshipton)
Also, black had an update and required some reformatting...
> Minor CI fixes

- .github/workflows/ci_pipeline.yml
- pySDC/helpers/firedrake_ensemble_communicator.py
- pySDC/tests/test_helpers/test_gusto_coupling.py
- pySDC/tutorial/step_7/F_pySDC_with_Gusto.py
After [some changes to Gusto](https://github.com/firedrakeproject/gusto/commit/81dedbde34e5e599239a329d50178e5b5e6a0ebb), some [strange deadlocks have started to appear in the pySDC tests](https://github.com/Parallel-in-Time/pySDC/actions/runs/13234132362/job/37084519438).
In the Gusto changes, a debug output showing the max/min values of some fields was added, which I presume requires communication across space. Removing this debug information is sufficient to get these tests to pass again.
In order to make sure the space-parallelism is set up correctly, I changed the MPI tests to always use four tasks and distribute them to do space-only, time-only, or space-time parallelism. All of these tests pass without the debug output.
This is definitely some fishy business. Do you know if the …
> Firedrake ensemble fix

- pySDC/implementations/problem_classes/TestEquation_0D.py
- pySDC/tests/test_problems/test_Dahlquist_IMEX.py
This is handy for testing IMEX schemes.. 
Note that our pipeline is pretty broken at the moment. We already have #528 to fix the failing Firedrake tests, but now there is another problem with Petsc that is unrelated to this PR, see [failing action on current pySDC main](https://github.com/Parallel-in-Time/pySDC/actions/runs/13234132362/job/37156886297).
> Added IMEX Dahlquist equation

- .gitignore
- etc/environment-base.yml
- pySDC/helpers/blocks.py
- pySDC/helpers/fieldsIO.py
- pySDC/helpers/vtk.py
- pySDC/helpers/vtkIO.py
- pySDC/tests/test_helpers/test_fieldsIO.py
- pySDC/tests/test_helpers/test_vtk.py
`Cart1D` and `Cart2D` have been replace by one `Rectilinear` class that does the same for all dimensions. It's not backward compatible, but since I was the only one using the old classes, it should be fine ...
> :warning: The new class uses some python 3.11+ features, allowing to extract slices of a ndarray by unpacking a list of slices. For instance :
```python
a = np.arange(2*3*4).reshape((2, 3, 4))
s = [0, slice(None), slice(2)]
a[*s]  # equivalent to a[0, :, :2]
``` 
While this is pretty neat to handle n-dimensional data without making the code too complicated, it's still seen as a syntax error in python 3.10 and lower. Hence the module requires now python 3.11 and higher, but it does not prevent to use pySDC with lower version (just do not import `pySDC.helpers.fieldsIO` ...)
Two …
> TL: generic FieldsIO class for n-dimensional rectilinear grids + VTK support

- .github/workflows/ci_pipeline.yml
- pySDC/tests/test_helpers/test_gusto_coupling.py
- pySDC/tests/test_tutorials/test_step_7.py
- pySDC/tutorial/step_7/E_pySDC_with_Firedrake.py
- pySDC/tutorial/step_7/F_pySDC_with_Gusto.py
Firedrake recently had some major changes to its installation. It can now be installed much easier with pip and I believe the Python does not have to be managed by Firedrake anymore. The Docker image was changed significantly to reflect that, breaking our tests.
This PR updates our tests to accommodate the changes. Note that I had to make some tolerances less tight. I have noticed before that changing the Python version changes roundoff errors and I assume that this is behind why I had to do had.
Please remember to squash and merge and replace the commit message with something shorter than the default..
> Fixing Firedrake tests

- pySDC/helpers/fieldsIO.py
- pySDC/tests/test_helpers/test_fieldsIO.py
Turns out that collective IO is much faster than individual operations when using FieldsIO within pySDC runs on HPC. This PR changes from individual to collective IO if possible and raises a warning if not. To be specific, you can generate a decomposition with uneven amount of data on the tasks, which prevents collective IO and probably leads to load balancing issues in other places as well, but you will get a warning telling you to change resolution / number of tasks.
There are a few other little things in this PR such as adding some missing pytest markers.
> Performance fix for FieldsIO

- pySDC/helpers/spectral_helper.py
This PR collects the extension of 1D matrices to ND matrices in a single function as opposed to duplicating them in every function that generates matrices. This only supports 1D and 2D, but in my development branch, I can extend up to 3D.
There are still some issues with the 3D branch, so it's going to be a bit longer until that PR comes.
> Small refactor of spectral helper to prepare for 3D

- etc/environment-mpi4py.yml
- pySDC/core/problem.py
- pySDC/helpers/fieldsIO.py
- pySDC/implementations/hooks/log_solution.py
- pySDC/implementations/problem_classes/TestEquation_0D.py
- pySDC/implementations/problem_classes/generic_spectral.py
- pySDC/projects/GPU/configs/GS_configs.py
- pySDC/projects/GPU/configs/RBC_configs.py
- pySDC/projects/GPU/tests/test_configs.py
- pySDC/tests/test_hooks/test_log_to_file.py
I added three functions to the core problem class, which I hope cover most cases:
- `setUpFieldsIO`: Mostly for setting up space decomposition. Here, you can call all the class methods of `FieldsIO` and derived classes
- `getOutputFile`: This function is supposed to instantiate a `FieldsIO` object fully set up, only taking a file name as an argument. This needs to be done individually for the problem classes to set the header and data structure correctly
- `processSolutionForOutput`: Do stuff to the solution before writing to the file. For instance, when using spectral methods, you may want to transform from spectral space to real space and throw away the imaginary part to save disc space.
Once these functions are set up for the problem class you want, you can simply add the hook …
> Implemented interface to FieldsIO in core problem class and respective hook

- pySDC/projects/Resilience/work_precision.py
These changes should be entirely inconsequential for anyone but me...
> Fixed some plots in thesis

- pySDC/projects/GPU/analysis_scripts/parallel_scaling.py
- pySDC/projects/GPU/paper_plots.py
- pySDC/projects/Resilience/paper_plots.py
Again, no need to worry about this. Just some changes to plots in my thesis.
> Slight changes to plots in thesis

- pySDC/helpers/fieldsIO.py
- pySDC/tests/test_benchmarks/test_collocation.py
- pySDC/tests/test_helpers/test_gusto_coupling.py
Remove the for loop with `mpi_write_at_all` to use only one write with a sub-array view. In particular, it avoids the need of the nCollectiveIO stuff, and makes the code way simpler.
> Always beneficial to know MPI features to avoid re-implementing those in a more clumsy way :sweat_smile:
> FieldsIO performance fix

- pySDC/helpers/fieldsIO.py
There is a rare situation when the `MPI_SETUP` method (setup the subarray view for MPI_READ_ALL) is not called when using MPI : when the `Rectilinear` object is instantiated first, and the MPI communicator and local slices are given by `setupMPI` after. This requires to read the header again, or else it raises and error.
While this is not the recommended usage for `Rectilinear` (`setupMPI` should be called before instantiating any class), this modification allows it while not changing the overall behavior or performance of the class.
> TL: mini fix for edge cases

- .github/workflows/ci_pipeline.yml
- pySDC/helpers/plot_helper.py
- pySDC/tests/test_benchmarks/test_collocation.py
Python `distutils` has been [deprecated since version 3.10 and removed in version 3.12](https://docs.python.org/3/library/distutils.html). In 3.12 I could still use it but after switching to 3.13, the plot helper was broken for me. 
Apparently,`distutil` has been replaced by `shutil`. `shutil.which` returns what you get when you use `which` in the shell you run Python in, or `None` if there is no executable of the name you are looking for. Therefore, this should give the same functionality as `distutil.spawn.find_executable` as it is used in the plot helper.
> Make plot helper compatible with Python 3.13

- pySDC/helpers/spectral_helper.py
- pySDC/tests/test_helpers/test_spectral_helper.py
Slightly more elaborate version of the test suggested by @tlunet in #554.
> Added test against memory leaks with cache decorator

- pySDC/projects/compression/Docker/install_pySDC.sh
The installation of mpi4py was broken with the [release of version 4.1.0](https://github.com/mpi4py/mpi4py/releases/tag/4.1.0). They added some pip wheel stuff, which seems incompatible with the docker image.
Note that the latest version of mpi4py does work in the container if installed without pulling the wheels, i.e. with `python -m pip install --no-binary :all: mpi4py`, but then the installation takes a bit longer which is why we decided to restrict the version instead.
> Fix failing libpressio tests

- .github/workflows/trigger_coverage_bot.yml
I do miss the Codecov bot posting about coverage in our PRs. I want to bring it back, but I don't know a lot about it, so maybe this will not actually do the trick.. I cannot test it before since this workflow will only be triggered once it is in the master branch.
What I added here is a separate workflow that runs when the GitHub CI is done and during PRs. All it does in that case is upload the coverage report to Codecov, which I assume will then trigger the bot.
Problem: Coverage will almost certainly be lower than in the master branch because the GPU tests are not included in this report. This should not lead to fluctuations in the coverage report, though, because the report is generated for a non-master branch and therefore does not show up in the tracking.
I suggest we bring back the …
> Added workflow for triggering the Codecov bot in PRs

- .github/workflows/trigger_coverage_bot.yml
Seems spaces are not allowed in job names, see [here](https://github.com/Parallel-in-Time/pySDC/actions/runs/15894913965).
> Fixed job name in Trigger coverage bot action

- pySDC/implementations/problem_classes/generic_spectral.py
- pySDC/tests/test_problems/test_heat_chebychev.py
This is for using iterative solvers in 3D RBC (PR coming as soon as this one is merged) together with incomplete LU as preconditioner.
> Refactored iterative solvers in generic spectral class

- pySDC/helpers/spectral_helper.py
- pySDC/implementations/problem_classes/RayleighBenard.py
- pySDC/implementations/problem_classes/generic_spectral.py
- pySDC/tests/test_helpers/test_spectral_helper.py
The spectral discretizations require a few block-diagonal matrices among all degrees of freedom. Constructing them as such actually reduces the memory requirements quite a bit compared to constructing general block matrices with only the diagonal blocks.
This is independent of the larger refactor, which is why I did a separate PR.
I added a test that the resulting operators are the same and that indeed memory is reduced.
> Reduced memory footprint of spectral discretizations via block-diagonal sparse operators

- pySDC/implementations/problem_classes/generic_spectral.py
- pySDC/tests/test_problems/test_RayleighBenard3D.py
- pySDC/tests/test_problems/test_generic_spectral.py
- pySDC/tests/test_problems/test_heat_chebychev.py
This PR has a few small things:
- There was a bug in the Dirichlet recombination (right preconditioner), which was never done
- Initial guesses are now correctly treated for the right preconditioner
- A few small tests including that the system matrices are actually banded once preconditioned
> Fix for spatial preconditioners in generic spectral problem class

- pySDC/helpers/spectral_helper.py
- pySDC/implementations/problem_classes/RayleighBenard.py
- pySDC/implementations/problem_classes/generic_spectral.py
- pySDC/tests/test_helpers/test_spectral_helper.py
In #565, I implemented dedicated functionality for block-diagonal matrices and said I didn't know why this uses less memory than constructing block-diagonal matrices from all possible blocks in scipy. I have since figured out why.
The memory size of a sparse matrix is proportional to the number of non-zero entries in the matrix. However, setting individual values in a matrix to zero does not remove them from storage, but keeps them around as non-zero entries with value zero. You have to eliminate zeros explicitly. See the following example:
```
import scipy.sparse as sp
N = 32
I = sp.eye(N).tocsc()
I.nnz  # N
I *= 0
I.nnz # N
I.eliminate_zeros()
I.nnz # 0
```
After adding `eliminate_zeros` after construction of linear operators, there is no more memory to be saved by using special …
> Eliminate zeros in sparse spectral operators

- pySDC/helpers/spectral_helper.py
This tiny refactor slightly improves setup of diagonal matrices in the spectral helper. The result is the same, but the code is shorter, faster and uses less memory. None of this in any meaningful way, but still..
> More efficient setup of diagonal matrices

- .gitlab-ci.yml
- etc/juwels_benchmark.sh
- etc/venv_juwels/activate.sh
- etc/venv_juwels/config.sh
- etc/venv_juwels/modules.sh
- etc/venv_juwels/readme.md
- etc/venv_juwels/requirements.txt
- etc/venv_juwels/setup.sh
- pySDC/tests/test_helpers/test_spectral_helper.py
second try.. This time without git submodules.
> Use sc_venv_template for tests on JUWELS

- pySDC/core/level.py
- pySDC/core/sweeper.py
- pySDC/helpers/setup_helper.py
- pySDC/implementations/convergence_controller_classes/adaptive_collocation.py
- pySDC/implementations/sweeper_classes/Multistep.py
- pySDC/implementations/sweeper_classes/Runge_Kutta.py
- pySDC/implementations/sweeper_classes/Runge_Kutta_Nystrom.py
- pySDC/implementations/sweeper_classes/boris_2nd_order.py
- pySDC/implementations/sweeper_classes/explicit.py
- pySDC/implementations/sweeper_classes/generic_implicit.py
- pySDC/implementations/sweeper_classes/generic_implicit_MPI.py
- pySDC/implementations/sweeper_classes/imex_1st_order.py
- pySDC/implementations/sweeper_classes/imex_1st_order_MPI.py
- pySDC/implementations/sweeper_classes/multi_implicit.py
- pySDC/implementations/sweeper_classes/verlet.py
- pySDC/projects/DAE/sweepers/fullyImplicitDAE.py
- pySDC/projects/DAE/sweepers/rungeKuttaDAE.py
- pySDC/projects/DAE/sweepers/semiImplicitDAE.py
- pySDC/projects/Monodomain/sweeper_classes/exponential_runge_kutta/imexexp_1st_order.py
- pySDC/projects/Monodomain/sweeper_classes/runge_kutta/imexexp_1st_order.py
- pySDC/projects/Second_orderSDC/tests/test_convergence.py
- pySDC/projects/parallelSDC/linearized_implicit_fixed_parallel.py
- pySDC/projects/parallelSDC/linearized_implicit_fixed_parallel_prec.py
- pySDC/projects/parallelSDC/linearized_implicit_parallel.py
- pySDC/projects/parallelSDC_reloaded/nilpotency.py
- pySDC/projects/soft_failure/implicit_sweeper_faults.py
- pySDC/tests/test_sweepers/test_preconditioners.py
As @danielru has correctly noted 10 years ago in #46, the sweepers can be instantiated, but not used without a level.
Since I now have some capacity for tending the garden, I thought I'd change that. 
I also think it makes it easier get started with developing a new sweeper since its now more obvious that sweeper and level interact.
Note that it is possible to pass `None` as the level in the SDC sweepers. The sweepers have setters for the level that make sure you pass a proper level, but they are not used during instantiation. In some tests, sweepers are instantiated to check the attached collocation problem, so we should keep this.
Closes #46
> Sweepers require level during instantiation

- pySDC/core/controller.py
When the code crashes, i.e. does not orderly finish, messages in the log that have not yet been flushed may not get flushed at all. Therefore, I was still using print statements a lot of the time which I removed when I was done.
The better approach is to flush all output immediately when running with debug output. Then, rather than adding temporary print statements during debugging, we can add meaningful messages and leave them in.
Now immediate flushing adds some overhead, I imagine, but presumably you don't care so much about performance when using debug output.
So this PR adds a handler for the loggers that immediately flushes if we use debug output, but it also gives a warning that this degrades performance.
Sadly, I don't know how to test this. If anyone has an idea, let me know!
> Immediately flush debug messages
