Parallel-in-Time/pySDC

- examples/SWFW/playground.py
Just made the plot created in the fast wave slow wave problem a little nicer.
> Labels for SWFW

- examples/acoustic_1d_imex/HookClass.py
- examples/acoustic_1d_imex/ProblemClass_conv.py
- examples/acoustic_1d_imex/buildFDMatrix.py
- examples/acoustic_1d_imex/buildWave1DMatrix.py
- examples/acoustic_1d_imex/plotconvdata.py
- examples/acoustic_1d_imex/runconvergence.py
- examples/acoustic_1d_imex/runitererror.py
Contains
- updates for the acoustic_1d_imex problem
- functions to generate and plot data showing convergence order in dt
- a function that computes and plots the convergence rate of fwsw-SDC for different acoustic wave speeds
> Iteration and convergence plots for fwsw SDC

- examples/boussinesq_2d_imex/HookClass.py
- examples/boussinesq_2d_imex/ProblemClass.py
- examples/boussinesq_2d_imex/rungmrescounter.py
- examples/boussinesq_2d_imex/standard_integrators.py
Adds functionality to compare total number of GMRES iterations required by fwsw-SDC and a DIRK method of order 2, 3, 4.
> Boussinesq

- examples/fwsw/plot_stability.py
Beatifies the stability plots. Also allows to plot for full collocation update as well as simply copy.
> Nicer stability plot

- examples/acoustic_1d_imex/plot_dispersion.py
- examples/acoustic_1d_imex/standard_integrators.py
Adds a function that plots the semi-discrete dispersion relation for SDC and DIRK for comparison.
> Function to plot semi-discrete dispersion relation

- examples/acoustic_1d_imex/plot_dispersion.py
Now correctly plots the phase speed instead of frequency. Also made plots smaller so that three fit into one row.
> Fix phase speed plots

- examples/acoustic_1d_imex/plot_dispersion.py
- examples/acoustic_1d_imex/standard_integrators.py
- examples/boussinesq_2d_imex/rungmrescounter.py
- examples/boussinesq_2d_imex/standard_integrators.py
Adds a fifth order RK IMEX, but that does not really give dramatically new insights.
> Add a fifth order rk imex

- examples/boussinesq_2d_imex/playground.py
Fixes parameter in playground.py in Boussinesq example so that it runs again.
> Fix playground in Boussinesq example

- examples/fwsw/plot_stability.py
Setting k=0 in plot_stability now plots stability domain of the collocation solution.
> Plot collocation stability

- examples/acoustic_1d_imex/ploterrorconstants.py
- examples/acoustic_1d_imex/runconvergence_rk.py
adds a script that plots the estimated error constants for fwsw-SDC and RK-IMEX.
> add script to plot the estimated error constants 

- examples/acoustic_1d_imex/HookClass.py
- examples/acoustic_1d_imex/plotenergy.py
- examples/acoustic_1d_imex/runenergy.py
Add scripts to generate and plot energy over time for fwsw-SDC, RK-IMEX and DIRK for 1d acoustic-advection example.
> Energy plots for acoustic-advection problem

- docs/source/index.rst
- docs/source/projects/error_estimation.rst
- docs/source/pySDC/core.rst
- docs/source/pySDC/implementations.controller_classes.rst
- docs/source/pySDC/implementations.problem_classes.rst
- docs/source/pySDC/implementations.rst
- pySDC/helpers/plot_helper.py
- pySDC/implementations/controller_classes/controller_nonMPI.py
- pySDC/projects/error_estimation/README.rst
- pySDC/projects/error_estimation/accuracy_check.py
- pySDC/projects/error_estimation/piline_hotrod_adaptivity.py
- pySDC/tests/test_projects/test_error_estimation/test_order.py
- pySDC/tests/test_projects/test_error_estimation/test_piline.py
Added a project including tests and documentation for error estimation and what to do with it, i.e. Hot Rod and adaptivity. Also, the plot_helper can now restore the defaults if an additional flag is passed to setup_mpl
> Put all the things in a project

- pySDC/helpers/stats_helper.py
- pySDC/tutorial/step_3/A_getting_statistics.py
Added a function that provides a bit of convenience to the stats module by calling sort_stats(filter_stats()) and sorts by time by default, such that you don't have to do it every time.
> Convenience in the stats helper

- pySDC/core/Problem.py
- pySDC/implementations/problem_classes/HeatEquation_2D_FD_periodic.py
- pySDC/tests/test_2d_fd_accuracy.py
I can also integrate this to further problems, but since I can't test them well easily, I didn't do that yet.
> Function to generate general finite difference stencils.

- pySDC/core/Controller.py
Added function for debugging that displays the convergence controllers and their order since otherwise it is easy to lose track of which is the last one to change the step size for instance
> Debugging function

- pySDC/implementations/problem_classes/HarmonicOscillator.py
- pySDC/implementations/sweeper_classes/boris_2nd_order.py
- pySDC/playgrounds/Boris/Dampedharmonic_oscillator_stability.py
- requirements.txt
I decided PR separately for the convergence and stability of SDC. In this branch, the main changes in boris_2nd_order.py and HarmonicOscillator.py.
> Stability sdc

- pySDC/core/Sweeper.py
- pySDC/playgrounds/Boris/penningtrap_HookClass.py
- pySDC/playgrounds/Boris/penningtrap_conv.py
Here, only convergence of SDC for the penning trap problem. A random initial guess was added in Sweeper.py and a new class was defined in peningtrap_HookClass.py to collect data for the convergence plot. peningtrap_conv.py compute the error and plot the results.
> Convergence sdc

- pySDC/core/Collocation.py
- pySDC/tests/test_collocation.py
> Safety modification when computing nodes in Collocation class

- pySDC/core/Controller.py
- pySDC/core/ConvergenceController.py
- pySDC/implementations/controller_classes/controller_nonMPI.py
- pySDC/implementations/convergence_controller_classes/adaptivity.py
- pySDC/implementations/convergence_controller_classes/basic_restarting_nonMPI.py
- pySDC/implementations/convergence_controller_classes/check_convergence.py
- pySDC/implementations/convergence_controller_classes/check_iteration_estimator.py
- pySDC/implementations/convergence_controller_classes/estimate_embedded_error.py
- pySDC/implementations/convergence_controller_classes/estimate_extrapolation_error.py
- pySDC/implementations/convergence_controller_classes/store_uold.py
- pySDC/playgrounds/compression/HookClass_error_output.py
- pySDC/playgrounds/compression/run_serial_examples.py
- pySDC/playgrounds/mpifft/grayscott.py
- pySDC/projects/Resilience/piline.py
- pySDC/tutorial/step_6/A_run_non_MPI_controller.py
- pySDC/tutorial/step_8/C_iteration_estimator.py
- pySDC/tutorial/step_8/HookClass_error_output.py
The convergence controllers are only implemented in the non MPI controller, so I didn't remove it from the MPI controller. Also, I think it could do with some more documentation on what actually happens. I changed it step8/C in the tutorial worked, but I am not always sure what's going on and if this will also work with multiple steps..
> Made a convergence controller out of `check_iteration_estimator`

- pySDC/implementations/convergence_controller_classes/adaptivity.py
- pySDC/implementations/convergence_controller_classes/hotrod.py
I plan to add this onto the embedded adaptivity to use it with the preconditioner optimisation stuff
> Added adaptivity based on the residual

- pySDC/playgrounds/Boris/Dampedharmonic_oscillator_stability.py
- pySDC/playgrounds/Boris/penningtrap_conv.py
I have changed to define quadrature nodes in my codes.
> quadrature type changed

- pySDC/implementations/sweeper_classes/boris_2nd_order.py
Now, boris_2nd_order works also for the Picard iteration.
> Boris 2nd order

- pySDC/core/ConvergenceController.py
- pySDC/core/Level.py
- pySDC/implementations/controller_classes/controller_MPI.py
- pySDC/implementations/controller_classes/controller_nonMPI.py
- pySDC/implementations/convergence_controller_classes/estimate_embedded_error.py
> removed embedded error estimate variable from Level

- pySDC/implementations/problem_classes/HeatEquation_ND_FD.py
- pySDC/projects/AsympConv/PFASST_conv_tests.py
I had to change some test in a project.
The frequency for the heat equation was set to -1, but the behaviour of the diffusion should be the same when setting it to +1. 
Instead, I want to use negative values, or in particular -1, for special configurations such as a Gaussian.
> Added Gaussian initial conditions to heat equation

- pySDC/core/Hooks.py
- pySDC/helpers/stats_helper.py
- pySDC/projects/Resilience/piline.py
@lisawim discovered some bug, which should be fixed by doing this. The modifications to the hook class look a bit off, but it should be fine.
> Fixed the filtering of values that have been recomputed

- pySDC/helpers/stats_helper.py
- pySDC/projects/PinTSimE/estimation_check_extended.py
I was fixing @lisawim's bug (which I implemented, but she discovered) in a special case scenario in my own use case before, which I didn't realise. As far as I understood her use case, this should be fixed now however.
> Bug was a bit more intricate than I thought

- pySDC/core/Controller.py
- pySDC/implementations/convergence_controller_classes/check_convergence.py
- pySDC/projects/Performance/controller_MPI_scorep.py
- pySDC/projects/PinTSimE/estimation_check.py
- pySDC/projects/deprecated/node_failure/controller_nonMPI_hard_faults.py
The function in the controller was indeed redundant, but it provided convenience. I changed the convergence controller to provide similar convenience. The function was only used in two places in the code anyways, which I am not sure if they are tested, however. But it should work in principle.
Closes #210
> Fix Issue210

- pySDC/projects/PinTSimE/estimation_check.py
- pySDC/projects/Resilience/test_Runge_Kutta_sweeper.py
- pySDC/tests/test_projects/test_resilience/test_rk.py
> Added tests for explicit RK methods

- pySDC/implementations/convergence_controller_classes/adaptivity.py
- pySDC/projects/Resilience/piline.py
- pySDC/tests/test_projects/test_resilience/test_piline.py
> Added test for residual based adaptivity

- pySDC/tests/test_nodes.py
> TL: added tests for nodes generation

- pySDC/projects/Resilience/FDeigenvalues.py
- pySDC/tests/test_projects/test_resilience/test_FD_eigenvalues.py
Now the tests are actually executed 🎉
> Moved test of computation of FD eigenvalues to test directory

- pySDC/helpers/problem_helper.py
- pySDC/implementations/problem_classes/LeakySuperconductor.py
- pySDC/projects/Resilience/leaky_superconductor.py
- pySDC/tests/test_projects/test_resilience/test_leaky_superconductor.py
This problem is interesting since the temperature of the domain at some point rises suddenly after a period of staying virtually constant, which is a good showcase for adaptivity.
The equation was proposed by @eschnaubelt during the Time-X Apps Hackathon as a toy version of something he works with in a "serious" code. 
In some cases it is required to impose an upper bound on the step size when using adaptivity with this problem. Otherwise the transition between low temperature and rapid heating is sometimes not resolved in time.
There is both an IMEX version and a fully implicit version, with the fully implicit version seeming more robust w.r.t. this issue.
Since it's the first time for me with Neumann boundary conditions in finite differences, maybe someone can check that I implemented …
> Adding toy problem to model superconductor with temperature leak

- pySDC/core/Problem.py
- pySDC/implementations/problem_classes/Lorenz.py
- pySDC/implementations/problem_classes/NonlinearSchroedinger_MPIFFT.py
- pySDC/implementations/problem_classes/Van_der_Pol_implicit.py
I was hoping for performance gain when inverting the Jacobian beforehand, but it doesn't seem to make much of a difference. I still think it's cleaner this way.
I added a few work counters along the way.
This is one of many PRs where I merge what I did in the past weeks one by one.
On the branch where I have all changes, the pipeline is broken for reasons that I don't understand. Some MPI error in the fenics environment... Anyways, I merge small changes now, so good for you ;)
> Manually inverted Jacobian for Lorenz problem

- docs/source/projects/doc_SDC_showdown.rst
- docs/source/projects/doc_asympconv.rst
- docs/source/projects/doc_fput.rst
- docs/source/projects/doc_fwsw_acoustic.rst
- docs/source/projects/doc_fwsw_boussinesq.rst
- docs/source/projects/doc_fwsw_theory.rst
- docs/source/projects/doc_hamiltonian_simple.rst
- docs/source/projects/doc_parallelSDC_nonlinear.rst
- docs/source/projects/doc_parallelSDC_preconditioner.rst
- docs/source/projects/doc_parallelSDC_preconditioner_MPI.rst
- docs/source/projects/doc_solar_system.rst
- docs/source/tutorial/doc_step_1_B.rst
- docs/source/tutorial/doc_step_1_D.rst
- docs/source/tutorial/doc_step_8_A.rst
- docs/source/tutorial/doc_step_8_B.rst
Plots can be found by going a level up and then into the data-dir
The data-dir does not exist in the sub-dirs (e.g. projects, tutorial) but instead on next to the sub-dirs,
therefore another relativ path is needed.
> Updated path to plots

- .github/workflows/ci_pipeline.yml
- docs/source/index.rst
- docs/source/projects/compression.rst
- pySDC/implementations/hooks/log_errors.py
- pySDC/projects/Resilience/advection.py
- pySDC/projects/compression/Docker/Dockerfile
- pySDC/projects/compression/Docker/Readme.rst
- pySDC/projects/compression/Docker/install_pySDC.sh
- pySDC/projects/compression/Readme.rst
- pySDC/projects/compression/compression_convergence_controller.py
- pySDC/projects/compression/order.py
- pySDC/tests/test_projects/test_compression/test_proof_of_concept.py
Please feel free to edit the Readme in the compression folder. I wrote some introduction on what I think the project is about, but you may have a more informed opinion.
> Added MPI support to the libpressio docker container and added the compression project to the website

- pySDC/core/Sweeper.py
- pySDC/implementations/controller_classes/controller_MPI.py
- pySDC/implementations/controller_classes/controller_nonMPI.py
- pySDC/implementations/convergence_controller_classes/check_convergence.py
- pySDC/implementations/sweeper_classes/Runge_Kutta.py
- pySDC/implementations/sweeper_classes/imex_1st_order_mass.py
- pySDC/projects/DAE/sweepers/fully_implicit_DAE.py
- pySDC/projects/Resilience/strategies.py
- pySDC/projects/Resilience/sweepers.py
- pySDC/projects/Resilience/vdp.py
- pySDC/projects/parallelSDC/generic_implicit_MPI.py
- pySDC/tests/test_Runge_Kutta_sweeper.py
- pySDC/tests/test_projects/test_resilience/test_efficient_sweepers.py
While the convergence of SDC is crucially dependent on computing the residual accurately, it is never explicitly used for SDC in this code, unless to declare convergence and to provide information about the convergence in the output.
This PR allows to skip computation of the residual in certain stages of the controller, which can be done manually with the result that the hooks will show incorrect, because not up to date, values for the residual, but you get speedup.
Because you have to manually set this, I don't think it will confuse new users.
This also applies to RK sweepers, which never need to compute the residual because they solve the "collocation problem" in a single iteration. The infrastructure is there that you can confirm that the residual is close to machine precision, but in …
> Computational efficiency by computing the residual fewer times

- pySDC/core/ConvergenceController.py
- pySDC/implementations/controller_classes/controller_MPI.py
- pySDC/implementations/convergence_controller_classes/adaptivity.py
- pySDC/implementations/convergence_controller_classes/basic_restarting.py
- pySDC/implementations/convergence_controller_classes/estimate_extrapolation_error.py
- pySDC/implementations/convergence_controller_classes/interpolate_between_restarts.py
- pySDC/implementations/convergence_controller_classes/spread_step_sizes.py
- pySDC/implementations/convergence_controller_classes/step_size_limiter.py
- pySDC/implementations/hooks/log_errors.py
- pySDC/projects/Resilience/strategies.py
- pySDC/projects/Resilience/vdp.py
- pySDC/projects/Resilience/work_precision.py
- pySDC/tests/test_projects/test_resilience/test_fault_injection.py
- pySDC/tests/test_projects/test_resilience/test_strategies.py
- pySDC/tests/test_projects/test_resilience/test_vdp.py
I opened this PR before, but because I indented too much, I created an MPI deadlock. Now the tests finally pass.
We already had the error estimate using this weird Taylor expansion within the Q matrix and this PR adds adaptivity based on that.
Also, some tests are now more fine grained, such that you can more easily see where something goes wrong, and some MPI tests should be a bit faster.
> Adaptivity using the error estimate by extrapolation within the quadrature rule.

- pySDC/implementations/problem_classes/PenningTrap_3D.py
- pySDC/implementations/sweeper_classes/Runge_Kutta_Nystrom.py
- pySDC/projects/Second_orderSDC/README.md
- pySDC/projects/Second_orderSDC/check_data_folder.py
- pySDC/projects/Second_orderSDC/dampedharmonic_oscillator_run_stability.py
- pySDC/projects/Second_orderSDC/penningtrap_HookClass.py
- pySDC/projects/Second_orderSDC/penningtrap_Simulation.py
- pySDC/projects/Second_orderSDC/penningtrap_run_error.py
- pySDC/projects/Second_orderSDC/penningtrap_run_work_precision.py
- pySDC/tests/test_projects/test_second_orderSDC/test_convergence.py
- pySDC/tests/test_projects/test_second_orderSDC/test_stability.py
Finally, I have made all of the code available for the second order SDC (Spectral Deferred Correction) paper. Here's what you can find:
1. In the projects' Second_orderSDC folder, I have created a directory where you can access all of the codes needed to implement the plots mentioned in the paper. For more information, please refer to the README file.
2. Additionally, I have included tests for the codes. These tests evaluate the convergence order of the Runge-Kutta-Nystrom method, the Velocity-Verlet scheme, and the SDC method. However, the SDC test only measures local convergence order as it requires less time to run.
3. I want to express my special thanks to @tlunet and @brownbaerchen for providing guidance and assistance in writing the codes.
I hope this clears up the information you …
> Second order sdc

- pySDC/implementations/problem_classes/AcousticAdvection_1D_FD_imex.py
- pySDC/implementations/problem_classes/BuckConverter.py
- pySDC/implementations/problem_classes/DiscontinuousTestODE.py
- pySDC/implementations/problem_classes/FastWaveSlowWave_0D.py
- pySDC/implementations/problem_classes/Lorenz.py
- pySDC/implementations/problem_classes/TestEquation_0D.py
- pySDC/implementations/problem_classes/Van_der_Pol_implicit.py
- pySDC/implementations/problem_classes/nonlinear_ODE_1.py
Documentation towards solving #286 with fixed typo's. This is an addition to the closed PR #340.
I'm so sorry for the circumstances.
> Documentation ONLY(!) for `acoustic_1d_imex`, `testequation0d` and `vanderpol` + fixed typo's

- pySDC/implementations/problem_classes/nonlinear_ODE_1.py
- pySDC/tests/test_problems/test_nonlinear_ODE_1.py
Starting with improving the test coverage of `pySDC` I added a small test for the `nonlinear_ODE_1` class. For this, I replaced the `ProblemError` in the `solve_system` method with a warning s.t. I can prove the number of Newton iterations.
> Small test for `nonlinear_ODE_1`

- pySDC/implementations/problem_classes/AllenCahn_MPIFFT.py
- pySDC/implementations/problem_classes/generic_ND_FD.py
Forgot two classes .. now, everything should be fine with this PR. I'm sorry for the circumstances!
> Addition to #358

- pySDC/implementations/problem_classes/AdvectionDiffusionEquation_1D_FFT.py
- pySDC/tests/test_problems/test_AdvectionDiffusionEquation_1D_FFT.py
- pySDC/tests/test_problems/test_AllenCahn_1D_FD.py
> Test for `AdvectionDiffusionEquation_1D_FFT.py`

- pySDC/core/Controller.py
- pySDC/core/ConvergenceController.py
- pySDC/core/Problem.py
- pySDC/helpers/problem_helper.py
- pySDC/implementations/convergence_controller_classes/estimate_embedded_error.py
- pySDC/implementations/hooks/log_errors.py
- pySDC/implementations/problem_classes/Lorenz.py
- pySDC/implementations/problem_classes/Van_der_Pol_implicit.py
- pySDC/implementations/sweeper_classes/imex_1st_order.py
- pySDC/projects/Resilience/collocation_adaptivity.py
I am now starting to merge back some stuff from my development branch as the plots for the paper are becoming more mature.
This first PR includes changes that are almost entirely cosmetic.
For instance, I was diff'ing some output from pySDC and the configuration was marked as different because the order was apparently random. You can sort the output from `dict.items()`, which will sort one of the entries alphabetically. Regardless of how it sorts, there is no difference if the configurations are the same with this.
> Cosmetic changes

- pySDC/playgrounds/ML_initial_guess/README.md
- pySDC/playgrounds/ML_initial_guess/heat.py
- pySDC/playgrounds/ML_initial_guess/ml_heat.py
- pySDC/playgrounds/ML_initial_guess/sweeper.py
- pySDC/playgrounds/ML_initial_guess/tensor.py
Together with @aqibrahimbt, we started a project to generate initial guesses for SDC with machine learning. The project is still in a very early stage and it is unclear if anybody will continue it.
Still, I think it makes sense to merge this into the main repository. It includes a PyTorch datatype for pySDC, which may be useful in the future. This is implemented in the most quick and dirty way imaginable. Very much WIP, but it enables counting iterations, so it's a good starting point.
Beyond that, we can actually generate initial guesses for a heat equation with a neural network. However, it doesn't work well because the network is overly simple. At this point we need someone with machine learning expertise and time on their hands to construct a better network.
Unfortunately, that …
> Started playground for generating initial guesses for SDC with machine learning

- README.md
Added the ExaOcean grant identified and the "Supported by the European Union - NextGenerationEU." clause that they would like us to display.
> Tentative to clean some branches

- pySDC/implementations/hooks/log_work.py
- pySDC/tests/test_hooks/test_log_work.py
I needed this again and thought it makes sense to put it where it belongs.
> Added hook for logging SDC iterations

- .github/workflows/gitlab_ci.yml
- .gitlab-ci.yml
An update of the gitlab-instance made some changes necessary. Fixing bugs to make Gitlab-CI run again.
Sorry for doing this in a PR instead of my own repo, but there, the Gitlab-CI is not triggered (i.e. this cannot be tested in my own repo).
Finished (and ready for review and merge), when changing from draft to actual PR
> Fix Gitlab-CI

- .github/workflows/ci_pipeline.yml
- .github/workflows/gitlab_ci.yml
- .github/workflows/postprocess.yml
- docs/contrib/02_continuous_integration.md
- pySDC/implementations/convergence_controller_classes/adaptive_collocation.py
- pySDC/projects/DAE/README.rst
- pySDC/projects/parallelSDC/preconditioner_playground_MPI.py
- pySDC/projects/parallelSDC/tests/test_preconditioner_MPI.py
- pySDC/tests/README.rst
New PR instead of #458, not with a branch that was rebased earlier (instead of master merged into branch)
Housekeeping for the website of pySDC including:
- Some updates on RST-Files (e.g. change duplicate names of links)
- Added plots for parallelSDC, so that they are included in the website
- Corrected some paths to images
- Building the website will now fail if images are not found and not included, to highlight this issue early when reappearing
> Maintaining website

- pySDC/helpers/stats_helper.py
- pySDC/implementations/problem_classes/AllenCahn_MPIFFT.py
- pySDC/implementations/problem_classes/NonlinearSchroedinger_MPIFFT.py
- pySDC/implementations/problem_classes/Van_der_Pol_implicit.py
- pySDC/playgrounds/DAE/linearTestDAEMinion.py
- pySDC/playgrounds/DAE/playground_MPI.py
- pySDC/projects/Resilience/AC.py
- pySDC/projects/Resilience/collocation_adaptivity.py
- pySDC/projects/Resilience/paper_plots.py
- pySDC/projects/Resilience/quench.py
- pySDC/projects/Resilience/strategies.py
- pySDC/projects/Resilience/tests/test_strategies.py
- pySDC/projects/Resilience/vdp.py
- pySDC/projects/Resilience/work_precision.py
- pySDC/tests/test_problems/test_quench.py
I had to change a lot of configurations for this, but not much in terms of functionality. I know it's a lot of mess. I apologise if anyone actually tries to review it :D I should have refactored at the time, but now I don't have time..
I also updated a reference for the exact solution of NLS and improved efficiency of the stats helper slightly. Van der Pol now allows relative Newton tolerance. 
Also, my git hook applies black to any file that is staged in my commits. Therefore, when I merge master, it reformats some of the files in playgrounds or tests that are not forced to be correctly formatted at that time. This includes two files in the DAE playground.
Finally, I added a small test that solver and RHS evaluation in Quench are consistent.
> Made new plots incorporating first review of adaptivity paper

- pySDC/implementations/sweeper_classes/Runge_Kutta.py
- pySDC/playgrounds/Allen_Cahn/AllenCahn_contracting_circle_standard_integrators.py
- pySDC/projects/DAE/sweepers/rungeKuttaDAE.py
- pySDC/tests/test_sweepers/test_Runge_Kutta_sweeper.py
Thanks to @mattfeldt for pointing this out
> Fixed spelling error in Crank-Nicolson (no h) scheme

- pySDC/implementations/hooks/log_solution.py
- pySDC/tests/test_hooks/test_log_to_file.py
Additionally, the `LogToFile` hook now stores the initial conditions.
> Added hook for storing solution to file after regular time increment

- pySDC/core/controller.py
- pySDC/implementations/convergence_controller_classes/interpolate_between_restarts.py
... and a tiny cleanup in the controller.
> Interpolate between restarts with IMEX mesh

- pySDC/implementations/sweeper_classes/Runge_Kutta.py
- pySDC/tests/test_sweepers/test_Runge_Kutta_sweeper.py
This is another method used in Dedalus for simple DAEs. Haven't found a suitable higher order one yet.
> Added ARK3 method
